# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityMixinAvatarSteerByCamera.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%AbilityMixinAvatarSteerByCamera.proto\x1a\x0cVector.proto\"[\n\x1f\x41\x62ilityMixinAvatarSteerByCamera\x12\x1b\n\ntarget_dir\x18\x07 \x01(\x0b\x32\x07.Vector\x12\x1b\n\ntarget_pos\x18\x02 \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityMixinAvatarSteerByCamera_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYMIXINAVATARSTEERBYCAMERA._serialized_start=55
  _ABILITYMIXINAVATARSTEERBYCAMERA._serialized_end=146
# @@protoc_insertion_point(module_scope)
