# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityMixinAvatarCombat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41\x62ilityMixinAvatarCombat.proto\"3\n\x18\x41\x62ilityMixinAvatarCombat\x12\x17\n\x0fis_enter_combat\x18\x06 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityMixinAvatarCombat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYMIXINAVATARCOMBAT._serialized_start=34
  _ABILITYMIXINAVATARCOMBAT._serialized_end=85
# @@protoc_insertion_point(module_scope)
