# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityScalarType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41\x62ilityScalarType.proto*\xed\x01\n\x11\x41\x62ilityScalarType\x12\x1f\n\x1b\x41\x42ILITY_SCALAR_TYPE_UNKNOWN\x10\x00\x12\x1d\n\x19\x41\x42ILITY_SCALAR_TYPE_FLOAT\x10\x01\x12\x1b\n\x17\x41\x42ILITY_SCALAR_TYPE_INT\x10\x02\x12\x1c\n\x18\x41\x42ILITY_SCALAR_TYPE_BOOL\x10\x03\x12\x1f\n\x1b\x41\x42ILITY_SCALAR_TYPE_TRIGGER\x10\x04\x12\x1e\n\x1a\x41\x42ILITY_SCALAR_TYPE_STRING\x10\x05\x12\x1c\n\x18\x41\x42ILITY_SCALAR_TYPE_UINT\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityScalarType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYSCALARTYPE._serialized_start=28
  _ABILITYSCALARTYPE._serialized_end=265
# @@protoc_insertion_point(module_scope)
