# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityInvocationsNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AbilityInvokeEntry_pb2 as AbilityInvokeEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41\x62ilityInvocationsNotify.proto\x1a\x18\x41\x62ilityInvokeEntry.proto\"@\n\x18\x41\x62ilityInvocationsNotify\x12$\n\x07invokes\x18\x02 \x03(\x0b\x32\x13.AbilityInvokeEntryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityInvocationsNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYINVOCATIONSNOTIFY._serialized_start=60
  _ABILITYINVOCATIONSNOTIFY._serialized_end=124
# @@protoc_insertion_point(module_scope)
