# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityActionTriggerAbility.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!AbilityActionTriggerAbility.proto\"/\n\x1b\x41\x62ilityActionTriggerAbility\x12\x10\n\x08other_id\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityActionTriggerAbility_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYACTIONTRIGGERABILITY._serialized_start=37
  _ABILITYACTIONTRIGGERABILITY._serialized_end=84
# @@protoc_insertion_point(module_scope)
