# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityMixinBreakout.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BreakoutSyncAction_pb2 as BreakoutSyncAction__pb2
import BreakoutSyncCreateConnect_pb2 as BreakoutSyncCreateConnect__pb2
import BreakoutSyncFinishGame_pb2 as BreakoutSyncFinishGame__pb2
import BreakoutSyncPing_pb2 as BreakoutSyncPing__pb2
import BreakoutSyncSnapShot_pb2 as BreakoutSyncSnapShot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41\x62ilityMixinBreakout.proto\x1a\x18\x42reakoutSyncAction.proto\x1a\x1f\x42reakoutSyncCreateConnect.proto\x1a\x1c\x42reakoutSyncFinishGame.proto\x1a\x16\x42reakoutSyncPing.proto\x1a\x1a\x42reakoutSyncSnapShot.proto\"\x8e\x04\n\x14\x41\x62ilityMixinBreakout\x12\x0f\n\x07retcode\x18\x08 \x01(\x05\x12\x31\n\tsync_type\x18\x04 \x01(\x0e\x32\x1e.AbilityMixinBreakout.SyncType\x12\x39\n\x13sync_create_connect\x18\x02 \x01(\x0b\x32\x1a.BreakoutSyncCreateConnectH\x00\x12&\n\tsync_ping\x18\x01 \x01(\x0b\x32\x11.BreakoutSyncPingH\x00\x12\x33\n\x10sync_finish_game\x18\x05 \x01(\x0b\x32\x17.BreakoutSyncFinishGameH\x00\x12/\n\x0esync_snap_shot\x18\x0e \x01(\x0b\x32\x15.BreakoutSyncSnapShotH\x00\x12*\n\x0bsync_action\x18\x03 \x01(\x0b\x32\x13.BreakoutSyncActionH\x00\"\xb4\x01\n\x08SyncType\x12\x12\n\x0eSYNC_TYPE_NONE\x10\x00\x12\x1c\n\x18SYNC_TYPE_CREATE_CONNECT\x10\x01\x12\x18\n\x14SYNC_TYPE_START_GAME\x10\x02\x12\x12\n\x0eSYNC_TYPE_PING\x10\x03\x12\x19\n\x15SYNC_TYPE_FINISH_GAME\x10\x04\x12\x17\n\x13SYNC_TYPE_SNAP_SHOT\x10\x05\x12\x14\n\x10SYNC_TYPE_ACTION\x10\x06\x42\x06\n\x04syncb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityMixinBreakout_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABILITYMIXINBREAKOUT._serialized_start=172
  _ABILITYMIXINBREAKOUT._serialized_end=698
  _ABILITYMIXINBREAKOUT_SYNCTYPE._serialized_start=510
  _ABILITYMIXINBREAKOUT_SYNCTYPE._serialized_end=690
# @@protoc_insertion_point(module_scope)
