# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityPlayOpenAnimNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ActivityPlayOpenAnimNotify.proto\"1\n\x1a\x41\x63tivityPlayOpenAnimNotify\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityPlayOpenAnimNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYPLAYOPENANIMNOTIFY._serialized_start=36
  _ACTIVITYPLAYOPENANIMNOTIFY._serialized_end=85
# @@protoc_insertion_point(module_scope)
