# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityTakeAllScoreRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ActivityTakeAllScoreRewardRsp.proto\"a\n\x1d\x41\x63tivityTakeAllScoreRewardRsp\x12\x1a\n\x12reward_config_list\x18\x0e \x03(\r\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x12\x13\n\x0b\x61\x63tivity_id\x18\x07 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityTakeAllScoreRewardRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYTAKEALLSCOREREWARDRSP._serialized_start=39
  _ACTIVITYTAKEALLSCOREREWARDRSP._serialized_end=136
# @@protoc_insertion_point(module_scope)
