# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityCondStateChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Uint32Pair_pb2 as Uint32Pair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ActivityCondStateChangeNotify.proto\x1a\x10Uint32Pair.proto\"\xe1\x01\n\x1d\x41\x63tivityCondStateChangeNotify\x12\x13\n\x0b\x61\x63tivity_id\x18\x05 \x01(\r\x12\x13\n\x0bschedule_id\x18\x0e \x01(\r\x12\x1b\n\x13Unk3300_HKKNIHNBHAE\x18\x01 \x03(\r\x12\x1b\n\x13Unk3300_BGNIBLKCPCA\x18\x04 \x03(\r\x12\x1e\n\x16\x61\x63tivated_sale_id_list\x18\x08 \x03(\r\x12<\n\'disable_transfer_point_interaction_list\x18\x0b \x03(\x0b\x32\x0b.Uint32Pairb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityCondStateChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYCONDSTATECHANGENOTIFY._serialized_start=58
  _ACTIVITYCONDSTATECHANGENOTIFY._serialized_end=283
# @@protoc_insertion_point(module_scope)
