# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityFriendGiftWishData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ProfilePicture_pb2 as ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ActivityFriendGiftWishData.proto\x1a\x14ProfilePicture.proto\"\xf0\x01\n\x1a\x41\x63tivityFriendGiftWishData\x12\x41\n\x0cgift_num_map\x18\x05 \x03(\x0b\x32+.ActivityFriendGiftWishData.GiftNumMapEntry\x12\x0b\n\x03uid\x18\x07 \x01(\r\x12(\n\x0fprofile_picture\x18\x0b \x01(\x0b\x32\x0f.ProfilePicture\x12\x13\n\x0bremark_name\x18\x0c \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x1a\x31\n\x0fGiftNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityFriendGiftWishData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYFRIENDGIFTWISHDATA_GIFTNUMMAPENTRY._options = None
  _ACTIVITYFRIENDGIFTWISHDATA_GIFTNUMMAPENTRY._serialized_options = b'8\001'
  _ACTIVITYFRIENDGIFTWISHDATA._serialized_start=59
  _ACTIVITYFRIENDGIFTWISHDATA._serialized_end=299
  _ACTIVITYFRIENDGIFTWISHDATA_GIFTNUMMAPENTRY._serialized_start=250
  _ACTIVITYFRIENDGIFTWISHDATA_GIFTNUMMAPENTRY._serialized_end=299
# @@protoc_insertion_point(module_scope)
