# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityGetRecvGiftListRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityRecvGiftData_pb2 as ActivityRecvGiftData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ActivityGetRecvGiftListRsp.proto\x1a\x1a\x41\x63tivityRecvGiftData.proto\"q\n\x1a\x41\x63tivityGetRecvGiftListRsp\x12\x13\n\x0bschedule_id\x18\x07 \x01(\r\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12-\n\x0erecv_gift_list\x18\n \x03(\x0b\x32\x15.ActivityRecvGiftDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityGetRecvGiftListRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYGETRECVGIFTLISTRSP._serialized_start=64
  _ACTIVITYGETRECVGIFTLISTRSP._serialized_end=177
# @@protoc_insertion_point(module_scope)
