# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityUpdateWatcherNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityWatcherInfo_pb2 as ActivityWatcherInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ActivityUpdateWatcherNotify.proto\x1a\x19\x41\x63tivityWatcherInfo.proto\"^\n\x1b\x41\x63tivityUpdateWatcherNotify\x12*\n\x0cwatcher_info\x18\x02 \x01(\x0b\x32\x14.ActivityWatcherInfo\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityUpdateWatcherNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYUPDATEWATCHERNOTIFY._serialized_start=64
  _ACTIVITYUPDATEWATCHERNOTIFY._serialized_end=158
# @@protoc_insertion_point(module_scope)
