# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityInfo_pb2 as ActivityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41\x63tivityInfoNotify.proto\x1a\x12\x41\x63tivityInfo.proto\":\n\x12\x41\x63tivityInfoNotify\x12$\n\ractivity_info\x18\x0c \x01(\x0b\x32\r.ActivityInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYINFONOTIFY._serialized_start=48
  _ACTIVITYINFONOTIFY._serialized_end=106
# @@protoc_insertion_point(module_scope)
