# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddBlacklistRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendBrief_pb2 as FriendBrief__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41\x64\x64\x42lacklistRsp.proto\x1a\x11\x46riendBrief.proto\"M\n\x0f\x41\x64\x64\x42lacklistRsp\x12)\n\x13target_friend_brief\x18\r \x01(\x0b\x32\x0c.FriendBrief\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddBlacklistRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDBLACKLISTRSP._serialized_start=44
  _ADDBLACKLISTRSP._serialized_end=121
# @@protoc_insertion_point(module_scope)
