# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdjustWorldLevelRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x41\x64justWorldLevelRsp.proto\"W\n\x13\x41\x64justWorldLevelRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x19\n\x11\x61\x66ter_world_level\x18\x0b \x01(\r\x12\x14\n\x0c\x63\x64_over_time\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AdjustWorldLevelRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADJUSTWORLDLEVELRSP._serialized_start=29
  _ADJUSTWORLDLEVELRSP._serialized_end=116
# @@protoc_insertion_point(module_scope)
