# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AllMarkPointNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MapMarkPoint_pb2 as MapMarkPoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41llMarkPointNotify.proto\x1a\x12MapMarkPoint.proto\"6\n\x12\x41llMarkPointNotify\x12 \n\tmark_list\x18\x07 \x03(\x0b\x32\r.MapMarkPointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AllMarkPointNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALLMARKPOINTNOTIFY._serialized_start=48
  _ALLMARKPOINTNOTIFY._serialized_end=102
# @@protoc_insertion_point(module_scope)
