# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArenaChallengeActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ArenaChallengeMonsterLevel_pb2 as ArenaChallengeMonsterLevel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ArenaChallengeActivityDetailInfo.proto\x1a ArenaChallengeMonsterLevel.proto\"\x94\x02\n ArenaChallengeActivityDetailInfo\x12/\n\nlevel_list\x18\x0f \x03(\x0b\x32\x1b.ArenaChallengeMonsterLevel\x12T\n\x13level_open_time_map\x18\x01 \x03(\x0b\x32\x37.ArenaChallengeActivityDetailInfo.LevelOpenTimeMapEntry\x12\x1b\n\x13is_finish_any_level\x18\x04 \x01(\x08\x12\x13\n\x0bworld_level\x18\x07 \x01(\r\x1a\x37\n\x15LevelOpenTimeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ArenaChallengeActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARENACHALLENGEACTIVITYDETAILINFO_LEVELOPENTIMEMAPENTRY._options = None
  _ARENACHALLENGEACTIVITYDETAILINFO_LEVELOPENTIMEMAPENTRY._serialized_options = b'8\001'
  _ARENACHALLENGEACTIVITYDETAILINFO._serialized_start=77
  _ARENACHALLENGEACTIVITYDETAILINFO._serialized_end=353
  _ARENACHALLENGEACTIVITYDETAILINFO_LEVELOPENTIMEMAPENTRY._serialized_start=298
  _ARENACHALLENGEACTIVITYDETAILINFO_LEVELOPENTIMEMAPENTRY._serialized_end=353
# @@protoc_insertion_point(module_scope)
