# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArenaChallengeFinishNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ArenaChallengeChildChallengeInfo_pb2 as ArenaChallengeChildChallengeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ArenaChallengeFinishNotify.proto\x1a&ArenaChallengeChildChallengeInfo.proto\"\xac\x01\n\x1a\x41renaChallengeFinishNotify\x12\x1d\n\x15\x61rena_challenge_level\x18\r \x01(\r\x12\x1a\n\x12\x61rena_challenge_id\x18\x03 \x01(\r\x12?\n\x14\x63hild_challenge_list\x18\x02 \x03(\x0b\x32!.ArenaChallengeChildChallengeInfo\x12\x12\n\nis_success\x18\x0c \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ArenaChallengeFinishNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARENACHALLENGEFINISHNOTIFY._serialized_start=77
  _ARENACHALLENGEFINISHNOTIFY._serialized_end=249
# @@protoc_insertion_point(module_scope)
