# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AsterMidInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AsterMidDetailInfo_pb2 as AsterMidDetailInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41sterMidInfoNotify.proto\x1a\x18\x41sterMidDetailInfo.proto\"7\n\x12\x41sterMidInfoNotify\x12!\n\x04info\x18\x07 \x01(\x0b\x32\x13.AsterMidDetailInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AsterMidInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASTERMIDINFONOTIFY._serialized_start=54
  _ASTERMIDINFONOTIFY._serialized_end=109
# @@protoc_insertion_point(module_scope)
