# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarDieAnimationEndReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41vatarDieAnimationEndReq.proto\x1a\x0cVector.proto\"[\n\x18\x41vatarDieAnimationEndReq\x12\x1b\n\nreborn_pos\x18\x03 \x01(\x0b\x32\x07.Vector\x12\x10\n\x08\x64ie_guid\x18\x07 \x01(\x04\x12\x10\n\x08skill_id\x18\x08 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarDieAnimationEndReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVATARDIEANIMATIONENDREQ._serialized_start=48
  _AVATARDIEANIMATIONENDREQ._serialized_end=139
# @@protoc_insertion_point(module_scope)
