# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarSkillInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarSkillInfo_pb2 as AvatarSkillInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41vatarSkillInfoNotify.proto\x1a\x15\x41vatarSkillInfo.proto\"\xa1\x01\n\x15\x41vatarSkillInfoNotify\x12\x37\n\tskill_map\x18\x06 \x03(\x0b\x32$.AvatarSkillInfoNotify.SkillMapEntry\x12\x0c\n\x04guid\x18\x04 \x01(\x04\x1a\x41\n\rSkillMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.AvatarSkillInfo:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarSkillInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVATARSKILLINFONOTIFY_SKILLMAPENTRY._options = None
  _AVATARSKILLINFONOTIFY_SKILLMAPENTRY._serialized_options = b'8\001'
  _AVATARSKILLINFONOTIFY._serialized_start=55
  _AVATARSKILLINFONOTIFY._serialized_end=216
  _AVATARSKILLINFONOTIFY_SKILLMAPENTRY._serialized_start=151
  _AVATARSKILLINFONOTIFY_SKILLMAPENTRY._serialized_end=216
# @@protoc_insertion_point(module_scope)
