# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarEquipAffixStartNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarEquipAffixInfo_pb2 as AvatarEquipAffixInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!AvatarEquipAffixStartNotify.proto\x1a\x1a\x41vatarEquipAffixInfo.proto\"c\n\x1b\x41vatarEquipAffixStartNotify\x12\x13\n\x0b\x61vatar_guid\x18\x01 \x01(\x04\x12/\n\x10\x65quip_affix_info\x18\t \x01(\x0b\x32\x15.AvatarEquipAffixInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarEquipAffixStartNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVATAREQUIPAFFIXSTARTNOTIFY._serialized_start=65
  _AVATAREQUIPAFFIXSTARTNOTIFY._serialized_end=164
# @@protoc_insertion_point(module_scope)
