# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarDieAnimationEndRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41vatarDieAnimationEndRsp.proto\"O\n\x18\x41vatarDieAnimationEndRsp\x12\x10\n\x08skill_id\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x12\x10\n\x08\x64ie_guid\x18\x0f \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarDieAnimationEndRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVATARDIEANIMATIONENDRSP._serialized_start=34
  _AVATARDIEANIMATIONENDRSP._serialized_end=113
# @@protoc_insertion_point(module_scope)
