# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BartenderLevelInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42\x61rtenderLevelInfo.proto\"F\n\x12\x42\x61rtenderLevelInfo\x12\n\n\x02id\x18\x0c \x01(\r\x12\x11\n\tis_finish\x18\x03 \x01(\x08\x12\x11\n\tmax_score\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BartenderLevelInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BARTENDERLEVELINFO._serialized_start=28
  _BARTENDERLEVELINFO._serialized_end=98
# @@protoc_insertion_point(module_scope)
