# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattlePassSchedule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattlePassCycle_pb2 as BattlePassCycle__pb2
import BattlePassProduct_pb2 as BattlePassProduct__pb2
import BattlePassRewardTag_pb2 as BattlePassRewardTag__pb2
import BattlePassUnlockStatus_pb2 as BattlePassUnlockStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42\x61ttlePassSchedule.proto\x1a\x15\x42\x61ttlePassCycle.proto\x1a\x17\x42\x61ttlePassProduct.proto\x1a\x19\x42\x61ttlePassRewardTag.proto\x1a\x1c\x42\x61ttlePassUnlockStatus.proto\"\x8b\x03\n\x12\x42\x61ttlePassSchedule\x12\r\n\x05level\x18\x0e \x01(\r\x12\x12\n\nbegin_time\x18\x02 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x0f \x01(\r\x12\r\n\x05point\x18\x01 \x01(\r\x12#\n\tcur_cycle\x18\x04 \x01(\x0b\x32\x10.BattlePassCycle\x12.\n\runlock_status\x18\x07 \x01(\x0e\x32\x17.BattlePassUnlockStatus\x12/\n\x11reward_taken_list\x18\x0b \x03(\x0b\x32\x14.BattlePassRewardTag\x12\x18\n\x10\x63ur_cycle_points\x18\n \x01(\r\x12\x1b\n\x13Unk2700_ODHAAHEPFAG\x18\x0c \x01(\r\x12(\n\x0cproduct_info\x18\r \x01(\x0b\x32\x12.BattlePassProduct\x12\"\n\x1ais_extra_paid_reward_taken\x18\x06 \x01(\x08\x12\x11\n\tis_viewed\x18\x03 \x01(\x08\x12\x13\n\x0bschedule_id\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattlePassSchedule_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTLEPASSSCHEDULE._serialized_start=134
  _BATTLEPASSSCHEDULE._serialized_end=529
# @@protoc_insertion_point(module_scope)
