# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattlePassUnlockStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42\x61ttlePassUnlockStatus.proto*\x87\x01\n\x16\x42\x61ttlePassUnlockStatus\x12%\n!BATTLE_PASS_UNLOCK_STATUS_INVALID\x10\x00\x12\"\n\x1e\x42\x41TTLE_PASS_UNLOCK_STATUS_FREE\x10\x01\x12\"\n\x1e\x42\x41TTLE_PASS_UNLOCK_STATUS_PAID\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattlePassUnlockStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTLEPASSUNLOCKSTATUS._serialized_start=33
  _BATTLEPASSUNLOCKSTATUS._serialized_end=168
# @@protoc_insertion_point(module_scope)
