# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlessingGetFriendPicListRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BlessingFriendPicData_pb2 as BlessingFriendPicData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!BlessingGetFriendPicListRsp.proto\x1a\x1b\x42lessingFriendPicData.proto\"d\n\x1b\x42lessingGetFriendPicListRsp\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12\x34\n\x14\x66riend_pic_data_list\x18\x08 \x03(\x0b\x32\x16.BlessingFriendPicDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlessingGetFriendPicListRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLESSINGGETFRIENDPICLISTRSP._serialized_start=66
  _BLESSINGGETFRIENDPICLISTRSP._serialized_end=166
# @@protoc_insertion_point(module_scope)
