# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BonusActivityUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BonusActivityInfo_pb2 as BonusActivityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x42onusActivityUpdateNotify.proto\x1a\x17\x42onusActivityInfo.proto\"Q\n\x19\x42onusActivityUpdateNotify\x12\x34\n\x18\x62onus_activity_info_list\x18\x08 \x03(\x0b\x32\x12.BonusActivityInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BonusActivityUpdateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BONUSACTIVITYUPDATENOTIFY._serialized_start=60
  _BONUSACTIVITYUPDATENOTIFY._serialized_end=141
# @@protoc_insertion_point(module_scope)
