# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BounceConjuringGallerySettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExhibitionDisplayInfo_pb2 as ExhibitionDisplayInfo__pb2
import OnlinePlayerInfo_pb2 as OnlinePlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&BounceConjuringGallerySettleInfo.proto\x1a\x1b\x45xhibitionDisplayInfo.proto\x1a\x16OnlinePlayerInfo.proto\"\x90\x03\n BounceConjuringGallerySettleInfo\x12\x1b\n\x13Unk3300_PELHBJDMKAE\x18\x06 \x01(\r\x12\r\n\x05score\x18\x0f \x01(\r\x12O\n\x10gadget_count_map\x18\x03 \x03(\x0b\x32\x35.BounceConjuringGallerySettleInfo.GadgetCountMapEntry\x12\x1b\n\x13Unk3300_CNGOBOFDEOE\x18\x0b \x01(\r\x12\x1b\n\x13Unk3300_NKGFKLGDFAC\x18\x01 \x01(\r\x12&\n\x0bplayer_info\x18\x02 \x01(\x0b\x32\x11.OnlinePlayerInfo\x12\x0e\n\x06\x64\x61mage\x18\x0c \x01(\x02\x12\x1b\n\x13Unk3300_BJHCDKNFDFN\x18\x07 \x01(\r\x12)\n\tcard_list\x18\t \x03(\x0b\x32\x16.ExhibitionDisplayInfo\x1a\x35\n\x13GadgetCountMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BounceConjuringGallerySettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOUNCECONJURINGGALLERYSETTLEINFO_GADGETCOUNTMAPENTRY._options = None
  _BOUNCECONJURINGGALLERYSETTLEINFO_GADGETCOUNTMAPENTRY._serialized_options = b'8\001'
  _BOUNCECONJURINGGALLERYSETTLEINFO._serialized_start=96
  _BOUNCECONJURINGGALLERYSETTLEINFO._serialized_end=496
  _BOUNCECONJURINGGALLERYSETTLEINFO_GADGETCOUNTMAPENTRY._serialized_start=443
  _BOUNCECONJURINGGALLERYSETTLEINFO_GADGETCOUNTMAPENTRY._serialized_end=496
# @@protoc_insertion_point(module_scope)
