# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BrickBreakerActivityStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#BrickBreakerActivityStageInfo.proto\"k\n\x1d\x42rickBreakerActivityStageInfo\x12\x10\n\x08stage_id\x18\x03 \x01(\r\x12\x1b\n\x13Unk3300_ALOGIKNHEIM\x18\x02 \x01(\x08\x12\x1b\n\x13Unk3300_FFKIEDNGNGK\x18\n \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BrickBreakerActivityStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BRICKBREAKERACTIVITYSTAGEINFO._serialized_start=39
  _BRICKBREAKERACTIVITYSTAGEINFO._serialized_end=146
# @@protoc_insertion_point(module_scope)
