# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BrickBreakerPlayerBattleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"BrickBreakerPlayerBattleInfo.proto\"\x9f\x01\n\x1c\x42rickBreakerPlayerBattleInfo\x12\x10\n\x08is_ready\x18\x07 \x01(\x08\x12\x12\n\ncostume_id\x18\x05 \x03(\r\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\r \x01(\r\x12\x11\n\tavatar_id\x18\t \x03(\r\x12\x13\n\x0bis_changing\x18\x0f \x01(\x08\x12\x12\n\nskill_list\x18\x03 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BrickBreakerPlayerBattleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BRICKBREAKERPLAYERBATTLEINFO._serialized_start=39
  _BRICKBREAKERPLAYERBATTLEINFO._serialized_end=198
# @@protoc_insertion_point(module_scope)
