# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuoyantCombatGallerySettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$BuoyantCombatGallerySettleInfo.proto\"\xda\x01\n\x1e\x42uoyantCombatGallerySettleInfo\x12\x15\n\rgallery_level\x18\x0b \x01(\r\x12\x1a\n\x12kill_monster_count\x18\x01 \x01(\r\x12\"\n\x1akill_special_monster_count\x18\t \x01(\r\x12\x1b\n\x13Unk3300_HLFHLPEKOML\x18\x07 \x01(\r\x12\x12\n\ngallery_id\x18\x02 \x01(\r\x12\x1b\n\x13Unk3300_KPCJBOOGEMG\x18\n \x01(\r\x12\x13\n\x0b\x66inal_score\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BuoyantCombatGallerySettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUOYANTCOMBATGALLERYSETTLEINFO._serialized_start=41
  _BUOYANTCOMBATGALLERYSETTLEINFO._serialized_end=259
# @@protoc_insertion_point(module_scope)
