# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CancelFinishParentQuestNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CancelFinishParentQuestNotify.proto\"8\n\x1d\x43\x61ncelFinishParentQuestNotify\x12\x17\n\x0fparent_quest_id\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CancelFinishParentQuestNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CANCELFINISHPARENTQUESTNOTIFY._serialized_start=39
  _CANCELFINISHPARENTQUESTNOTIFY._serialized_end=95
# @@protoc_insertion_point(module_scope)
