# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CataLogGlobalWatcherFinishedData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&CataLogGlobalWatcherFinishedData.proto\"^\n CataLogGlobalWatcherFinishedData\x12$\n\x1c\x66inished_global_watcher_list\x18\x0f \x03(\r\x12\x14\n\x0c\x63\x61talog_type\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CataLogGlobalWatcherFinishedData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATALOGGLOBALWATCHERFINISHEDDATA._serialized_start=42
  _CATALOGGLOBALWATCHERFINISHEDDATA._serialized_end=136
# @@protoc_insertion_point(module_scope)
