# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabEnterLoopDungeonRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ChannelerSlabEnterLoopDungeonRsp.proto\"\x8e\x01\n ChannelerSlabEnterLoopDungeonRsp\x12\x10\n\x08point_id\x18\x0e \x01(\r\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12\x15\n\rdifficulty_id\x18\x08 \x01(\r\x12\x15\n\rdungeon_index\x18\r \x01(\r\x12\x19\n\x11\x63ondition_id_list\x18\x07 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabEnterLoopDungeonRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABENTERLOOPDUNGEONRSP._serialized_start=43
  _CHANNELERSLABENTERLOOPDUNGEONRSP._serialized_end=185
# @@protoc_insertion_point(module_scope)
