# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabLoopDungeonStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChannelerSlabLoopDungeonInfo_pb2 as ChannelerSlabLoopDungeonInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ChannelerSlabLoopDungeonStageInfo.proto\x1a\"ChannelerSlabLoopDungeonInfo.proto\"\xbe\x01\n!ChannelerSlabLoopDungeonStageInfo\x12\x38\n\x11\x64ungeon_info_list\x18\x0f \x03(\x0b\x32\x1d.ChannelerSlabLoopDungeonInfo\x12\x1f\n\x17taken_reward_index_list\x18\x05 \x03(\r\x12\x0f\n\x07is_open\x18\x0b \x01(\x08\x12\x1a\n\x12last_difficulty_id\x18\x06 \x01(\r\x12\x11\n\topen_time\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabLoopDungeonStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABLOOPDUNGEONSTAGEINFO._serialized_start=80
  _CHANNELERSLABLOOPDUNGEONSTAGEINFO._serialized_end=270
# @@protoc_insertion_point(module_scope)
