# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabSaveAssistInfoReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChannelerSlabAssistInfo_pb2 as ChannelerSlabAssistInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ChannelerSlabSaveAssistInfoReq.proto\x1a\x1d\x43hannelerSlabAssistInfo.proto\"T\n\x1e\x43hannelerSlabSaveAssistInfoReq\x12\x32\n\x10\x61ssist_info_list\x18\x08 \x03(\x0b\x32\x18.ChannelerSlabAssistInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabSaveAssistInfoReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABSAVEASSISTINFOREQ._serialized_start=71
  _CHANNELERSLABSAVEASSISTINFOREQ._serialized_end=155
# @@protoc_insertion_point(module_scope)
