# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabAssistInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43hannelerSlabAssistInfo.proto\"O\n\x17\x43hannelerSlabAssistInfo\x12\x14\n\x0c\x61vatar_level\x18\n \x01(\r\x12\x0b\n\x03uid\x18\x0b \x01(\r\x12\x11\n\tavatar_id\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabAssistInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABASSISTINFO._serialized_start=33
  _CHANNELERSLABASSISTINFO._serialized_end=112
# @@protoc_insertion_point(module_scope)
