# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChangeHpReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43hangeHpReason.proto*\xac\x08\n\x0e\x43hangeHpReason\x12\x19\n\x15\x43HANGE_HP_REASON_NONE\x10\x00\x12\x1f\n\x1b\x43HANGE_HP_REASON_SUB_AVATAR\x10\x01\x12 \n\x1c\x43HANGE_HP_REASON_SUB_MONSTER\x10\x02\x12\x1d\n\x19\x43HANGE_HP_REASON_SUB_GEAR\x10\x03\x12\x1e\n\x1a\x43HANGE_HP_REASON_SUB_ENVIR\x10\x04\x12\x1d\n\x19\x43HANGE_HP_REASON_SUB_FALL\x10\x05\x12\x1e\n\x1a\x43HANGE_HP_REASON_SUB_DRAWN\x10\x06\x12\x1e\n\x1a\x43HANGE_HP_REASON_SUB_ABYSS\x10\x07\x12 \n\x1c\x43HANGE_HP_REASON_SUB_ABILITY\x10\x08\x12\x1f\n\x1b\x43HANGE_HP_REASON_SUB_SUMMON\x10\t\x12\x1f\n\x1b\x43HANGE_HP_REASON_SUB_SCRIPT\x10\n\x12\x1b\n\x17\x43HANGE_HP_REASON_SUB_GM\x10\x0b\x12\"\n\x1e\x43HANGE_HP_REASON_SUB_KILL_SELF\x10\x0c\x12%\n!CHANGE_HP_REASON_SUB_CLIMATE_COLD\x10\r\x12(\n$CHANGE_HP_REASON_SUB_STORM_LIGHTNING\x10\x0e\x12+\n\'CHANGE_HP_REASON_SUB_KILL_SERVER_GADGET\x10\x0f\x12 \n\x1c\x43HANGE_HP_REASON_SUB_REPLACE\x10\x10\x12%\n!CHANGE_HP_REASON_SUB_PLAYER_LEAVE\x10\x11\x12(\n$CHANGE_HP_REASON_Unk2700_CIKCDBOJGDK\x10\x12\x12(\n$CHANGE_HP_REASON_Unk2700_HEKLBLFBJJK\x10\x13\x12\x1b\n\x17\x43HANGE_HP_REASON_BY_LUA\x10\x33\x12 \n\x1c\x43HANGE_HP_REASON_ADD_ABILITY\x10\x65\x12\x1d\n\x19\x43HANGE_HP_REASON_ADD_ITEM\x10\x66\x12\x1f\n\x1b\x43HANGE_HP_REASON_ADD_REVIVE\x10g\x12 \n\x1c\x43HANGE_HP_REASON_ADD_UPGRADE\x10h\x12\x1f\n\x1b\x43HANGE_HP_REASON_ADD_STATUE\x10i\x12#\n\x1f\x43HANGE_HP_REASON_ADD_BACKGROUND\x10j\x12\x1b\n\x17\x43HANGE_HP_REASON_ADD_GM\x10k\x12.\n*CHANGE_HP_REASON_ADD_TRIAL_AVATAR_ACTIVITY\x10l\x12*\n&CHANGE_HP_REASON_ADD_ROUGUELIKE_SPRING\x10mb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChangeHpReason_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANGEHPREASON._serialized_start=25
  _CHANGEHPREASON._serialized_end=1093
# @@protoc_insertion_point(module_scope)
