# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabLoopDungeonSelectConditionRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0ChannelerSlabLoopDungeonSelectConditionRsp.proto\"\x86\x01\n*ChannelerSlabLoopDungeonSelectConditionRsp\x12\x15\n\rdungeon_index\x18\x01 \x01(\r\x12\x19\n\x11\x63ondition_id_list\x18\n \x03(\r\x12\x15\n\rdifficulty_id\x18\x05 \x01(\r\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabLoopDungeonSelectConditionRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABLOOPDUNGEONSELECTCONDITIONRSP._serialized_start=53
  _CHANNELERSLABLOOPDUNGEONSELECTCONDITIONRSP._serialized_end=187
# @@protoc_insertion_point(module_scope)
