# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelerSlabWearBuffRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x43hannelerSlabWearBuffRsp.proto\"\\\n\x18\x43hannelerSlabWearBuffRsp\x12\x0f\n\x07\x62uff_id\x18\x0f \x01(\r\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\r\n\x05is_mp\x18\t \x01(\x08\x12\x0f\n\x07slot_id\x18\x08 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelerSlabWearBuffRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELERSLABWEARBUFFRSP._serialized_start=34
  _CHANNELERSLABWEARBUFFRSP._serialized_end=126
# @@protoc_insertion_point(module_scope)
