# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckUgcUpdateReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UgcType_pb2 as UgcType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43heckUgcUpdateReq.proto\x1a\rUgcType.proto\"/\n\x11\x43heckUgcUpdateReq\x12\x1a\n\x08ugc_type\x18\x03 \x01(\x0e\x32\x08.UgcTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CheckUgcUpdateReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKUGCUPDATEREQ._serialized_start=42
  _CHECKUGCUPDATEREQ._serialized_end=89
# @@protoc_insertion_point(module_scope)
