# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckSegmentCRCNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SegmentInfo_pb2 as SegmentInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43heckSegmentCRCNotify.proto\x1a\x11SegmentInfo.proto\"8\n\x15\x43heckSegmentCRCNotify\x12\x1f\n\tinfo_list\x18\x06 \x03(\x0b\x32\x0c.SegmentInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CheckSegmentCRCNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKSEGMENTCRCNOTIFY._serialized_start=50
  _CHECKSEGMENTCRCNOTIFY._serialized_end=106
# @@protoc_insertion_point(module_scope)
