# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43hessActivityDetailInfo.proto\"\x81\x02\n\x17\x43hessActivityDetailInfo\x12\x18\n\x10punish_over_time\x18\t \x01(\r\x12\x1b\n\x13Unk3300_LPDDFGGKGBP\x18\x04 \x01(\r\x12\r\n\x05level\x18\x0e \x01(\r\x12\x0b\n\x03\x65xp\x18\x06 \x01(\r\x12\x1b\n\x13Unk3300_HBGEGIPIANG\x18\x0f \x01(\r\x12\x1a\n\x12\x63ontent_close_time\x18\x01 \x01(\r\x12!\n\x19is_teach_dungeon_finished\x18\x0b \x01(\x08\x12\x19\n\x11is_content_closed\x18\x05 \x01(\x08\x12\x1c\n\x14\x66inished_map_id_list\x18\r \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHESSACTIVITYDETAILINFO._serialized_start=34
  _CHESSACTIVITYDETAILINFO._serialized_end=291
# @@protoc_insertion_point(module_scope)
