# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CityReputationHuntInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ityReputationHuntInfo.proto\"Z\n\x16\x43ityReputationHuntInfo\x12\x1b\n\x13\x63ur_week_finish_num\x18\x01 \x01(\r\x12\x0f\n\x07is_open\x18\x07 \x01(\x08\x12\x12\n\nhas_reward\x18\x0f \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CityReputationHuntInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITYREPUTATIONHUNTINFO._serialized_start=32
  _CITYREPUTATIONHUNTINFO._serialized_end=122
# @@protoc_insertion_point(module_scope)
