# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientScriptEventNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43lientScriptEventNotify.proto\"u\n\x17\x43lientScriptEventNotify\x12\x12\n\nparam_list\x18\t \x03(\x05\x12\x18\n\x10source_entity_id\x18\x0e \x01(\r\x12\x12\n\nevent_type\x18\n \x01(\r\x12\x18\n\x10target_entity_id\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientScriptEventNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTSCRIPTEVENTNOTIFY._serialized_start=33
  _CLIENTSCRIPTEVENTNOTIFY._serialized_end=150
# @@protoc_insertion_point(module_scope)
