# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoinCollectCheckDoubleStartPlayReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(CoinCollectCheckDoubleStartPlayReq.proto\"6\n\"CoinCollectCheckDoubleStartPlayReq\x12\x10\n\x08level_id\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoinCollectCheckDoubleStartPlayReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COINCOLLECTCHECKDOUBLESTARTPLAYREQ._serialized_start=44
  _COINCOLLECTCHECKDOUBLESTARTPLAYREQ._serialized_end=98
# @@protoc_insertion_point(module_scope)
