# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CombineFormulaDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x43ombineFormulaDataNotify.proto\"A\n\x18\x43ombineFormulaDataNotify\x12\x12\n\ncombine_id\x18\x06 \x01(\r\x12\x11\n\tis_locked\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CombineFormulaDataNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMBINEFORMULADATANOTIFY._serialized_start=34
  _COMBINEFORMULADATANOTIFY._serialized_end=99
# @@protoc_insertion_point(module_scope)
