# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonPlayerTipsNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ommonPlayerTipsNotify.proto\"G\n\x16\x43ommonPlayerTipsNotify\x12\x13\n\x0bnotify_type\x18\x03 \x01(\r\x12\x18\n\x10text_map_id_list\x18\t \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonPlayerTipsNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONPLAYERTIPSNOTIFY._serialized_start=32
  _COMMONPLAYERTIPSNOTIFY._serialized_end=103
# @@protoc_insertion_point(module_scope)
