# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoopChapterUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoopChapter_pb2 as CoopChapter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43oopChapterUpdateNotify.proto\x1a\x11\x43oopChapter.proto\"=\n\x17\x43oopChapterUpdateNotify\x12\"\n\x0c\x63hapter_list\x18\x0e \x03(\x0b\x32\x0c.CoopChapterb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoopChapterUpdateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COOPCHAPTERUPDATENOTIFY._serialized_start=52
  _COOPCHAPTERUPDATENOTIFY._serialized_end=113
# @@protoc_insertion_point(module_scope)
