# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateMassiveEntityReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ClientMassiveEntity_pb2 as ClientMassiveEntity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43reateMassiveEntityReq.proto\x1a\x19\x43lientMassiveEntity.proto\"K\n\x16\x43reateMassiveEntityReq\x12\x31\n\x13massive_entity_list\x18\x01 \x03(\x0b\x32\x14.ClientMassiveEntityb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateMassiveEntityReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEMASSIVEENTITYREQ._serialized_start=59
  _CREATEMASSIVEENTITYREQ._serialized_end=134
# @@protoc_insertion_point(module_scope)
