# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CrystalLinkSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43rystalLinkSettleInfo.proto\"\xad\x01\n\x15\x43rystalLinkSettleInfo\x12\x1e\n\x16kill_elite_monster_num\x18\x02 \x01(\r\x12\x13\n\x0b\x66inal_score\x18\x06 \x01(\r\x12\x10\n\x08level_id\x18\x0c \x01(\r\x12\x15\n\ris_new_record\x18\r \x01(\x08\x12\x15\n\rdifficulty_id\x18\t \x01(\r\x12\x1f\n\x17kill_normal_mosnter_num\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CrystalLinkSettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRYSTALLINKSETTLEINFO._serialized_start=32
  _CRYSTALLINKSETTLEINFO._serialized_end=205
# @@protoc_insertion_point(module_scope)
