# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomDungeonSocialMuipData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!CustomDungeonSocialMuipData.proto\"e\n\x1b\x43ustomDungeonSocialMuipData\x12\x10\n\x08play_num\x18\x01 \x01(\r\x12\x10\n\x08like_num\x18\x02 \x01(\r\x12\x11\n\tstore_num\x18\x03 \x01(\r\x12\x0f\n\x07win_num\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomDungeonSocialMuipData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMDUNGEONSOCIALMUIPDATA._serialized_start=37
  _CUSTOMDUNGEONSOCIALMUIPDATA._serialized_end=138
# @@protoc_insertion_point(module_scope)
