# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomDungeonAbstractMuipData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CustomDungeonAbstractMuipData.proto\"\xe7\x01\n\x1d\x43ustomDungeonAbstractMuipData\x12\x1a\n\x12\x66irst_publish_time\x18\x01 \x01(\r\x12\x19\n\x11last_publish_time\x18\x02 \x01(\r\x12T\n\x14\x62rick_statistics_map\x18\x03 \x03(\x0b\x32\x36.CustomDungeonAbstractMuipData.BrickStatisticsMapEntry\x1a\x39\n\x17\x42rickStatisticsMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomDungeonAbstractMuipData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMDUNGEONABSTRACTMUIPDATA_BRICKSTATISTICSMAPENTRY._options = None
  _CUSTOMDUNGEONABSTRACTMUIPDATA_BRICKSTATISTICSMAPENTRY._serialized_options = b'8\001'
  _CUSTOMDUNGEONABSTRACTMUIPDATA._serialized_start=40
  _CUSTOMDUNGEONABSTRACTMUIPDATA._serialized_end=271
  _CUSTOMDUNGEONABSTRACTMUIPDATA_BRICKSTATISTICSMAPENTRY._serialized_start=214
  _CUSTOMDUNGEONABSTRACTMUIPDATA_BRICKSTATISTICSMAPENTRY._serialized_end=271
# @@protoc_insertion_point(module_scope)
