# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DealAddFriendResultType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x44\x65\x61lAddFriendResultType.proto*i\n\x17\x44\x65\x61lAddFriendResultType\x12&\n\"DEAL_ADD_FRIEND_RESULT_TYPE_REJECT\x10\x00\x12&\n\"DEAL_ADD_FRIEND_RESULT_TYPE_ACCEPT\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DealAddFriendResultType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEALADDFRIENDRESULTTYPE._serialized_start=33
  _DEALADDFRIENDRESULTTYPE._serialized_end=138
# @@protoc_insertion_point(module_scope)
