# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DraftTwiceConfirmResultNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#DraftTwiceConfirmResultNotify.proto\"G\n\x1d\x44raftTwiceConfirmResultNotify\x12\x14\n\x0cis_all_argee\x18\x07 \x01(\x08\x12\x10\n\x08\x64raft_id\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DraftTwiceConfirmResultNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRAFTTWICECONFIRMRESULTNOTIFY._serialized_start=39
  _DRAFTTWICECONFIRMRESULTNOTIFY._serialized_end=110
# @@protoc_insertion_point(module_scope)
