# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DraftGuestReplyTwiceConfirmReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$DraftGuestReplyTwiceConfirmReq.proto\"D\n\x1e\x44raftGuestReplyTwiceConfirmReq\x12\x10\n\x08is_agree\x18\x0f \x01(\x08\x12\x10\n\x08\x64raft_id\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DraftGuestReplyTwiceConfirmReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRAFTGUESTREPLYTWICECONFIRMREQ._serialized_start=40
  _DRAFTGUESTREPLYTWICECONFIRMREQ._serialized_end=108
# @@protoc_insertion_point(module_scope)
