# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DragonSpineCoinChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!DragonSpineCoinChangeNotify.proto\"~\n\x1b\x44ragonSpineCoinChangeNotify\x12\x1a\n\x12shimmering_essence\x18\x04 \x01(\r\x12\x14\n\x0cwarm_essence\x18\r \x01(\r\x12\x13\n\x0bschedule_id\x18\x0c \x01(\r\x12\x18\n\x10wondrous_essence\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DragonSpineCoinChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRAGONSPINECOINCHANGENOTIFY._serialized_start=37
  _DRAGONSPINECOINCHANGENOTIFY._serialized_end=163
# @@protoc_insertion_point(module_scope)
