# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonCandidateTeamDismissReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'DungeonCandidateTeamDismissReason.proto*\xc9\x01\n!DungeonCandidateTeamDismissReason\x12\x35\n1DUNGEON_CANDIDATE_TEAM_DISMISS_REASON_TPDR_NORMAL\x10\x00\x12\x32\n.DUNGEON_CANDIDATE_TEAM_DISMISS_REASON_TPDR_DIE\x10\x01\x12\x39\n5DUNGEON_CANDIDATE_TEAM_DISMISS_REASON_TPDR_DISCONNECT\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonCandidateTeamDismissReason_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUNGEONCANDIDATETEAMDISMISSREASON._serialized_start=44
  _DUNGEONCANDIDATETEAMDISMISSREASON._serialized_end=245
# @@protoc_insertion_point(module_scope)
