# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonInterruptChallengeReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"DungeonInterruptChallengeReq.proto\"_\n\x1c\x44ungeonInterruptChallengeReq\x12\x17\n\x0f\x63hallenge_index\x18\x0e \x01(\r\x12\x10\n\x08group_id\x18\r \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonInterruptChallengeReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUNGEONINTERRUPTCHALLENGEREQ._serialized_start=38
  _DUNGEONINTERRUPTCHALLENGEREQ._serialized_end=133
# @@protoc_insertion_point(module_scope)
