# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonEntryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WeeklyBossResinDiscountInfo_pb2 as WeeklyBossResinDiscountInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44ungeonEntryInfo.proto\x1a!WeeklyBossResinDiscountInfo.proto\"\x98\x02\n\x10\x44ungeonEntryInfo\x12\x10\n\x08\x65nd_time\x18\x0e \x01(\r\x12\x1b\n\x13Unk3300_KNKFCOKMECI\x18\t \x01(\r\x12\x11\n\tis_passed\x18\r \x01(\x08\x12\x45\n\x1fweekly_boss_resin_discount_info\x18\x06 \x01(\x0b\x32\x1c.WeeklyBossResinDiscountInfo\x12\x12\n\ndungeon_id\x18\x08 \x01(\r\x12\x1b\n\x13Unk3300_IDMPGPKMMEH\x18\x05 \x01(\r\x12\x19\n\x11next_refresh_time\x18\n \x01(\r\x12\x1b\n\x13Unk3300_ONLALCCKIEE\x18\x03 \x01(\r\x12\x12\n\nstart_time\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonEntryInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUNGEONENTRYINFO._serialized_start=62
  _DUNGEONENTRYINFO._serialized_end=342
# @@protoc_insertion_point(module_scope)
