# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonCandidateTeamInviteNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&DungeonCandidateTeamInviteNotify.proto\"k\n DungeonCandidateTeamInviteNotify\x12\x12\n\nplayer_uid\x18\x05 \x01(\r\x12\x1f\n\x17vaild_deadline_time_sec\x18\t \x01(\r\x12\x12\n\ndungeon_id\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonCandidateTeamInviteNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUNGEONCANDIDATETEAMINVITENOTIFY._serialized_start=42
  _DUNGEONCANDIDATETEAMINVITENOTIFY._serialized_end=149
# @@protoc_insertion_point(module_scope)
