# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonCandidateTeamInviteRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#DungeonCandidateTeamInviteRsp.proto\"M\n\x1d\x44ungeonCandidateTeamInviteRsp\x12\x1b\n\x13invalid_player_uids\x18\x0b \x03(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonCandidateTeamInviteRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUNGEONCANDIDATETEAMINVITERSP._serialized_start=39
  _DUNGEONCANDIDATETEAMINVITERSP._serialized_end=116
# @@protoc_insertion_point(module_scope)
