# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DynamicSVONode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44ynamicSVONode.proto\x1a\x0cVector.proto\"I\n\x0e\x44ynamicSVONode\x12\x0c\n\x04\x61rea\x18\x03 \x01(\x05\x12\x1a\n\trefer_pos\x18\x0f \x01(\x0b\x32\x07.Vector\x12\r\n\x05index\x18\x02 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DynamicSVONode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DYNAMICSVONODE._serialized_start=38
  _DYNAMICSVONODE._serialized_end=111
# @@protoc_insertion_point(module_scope)
