# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DynamicNodes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DynamicLayerNodes_pb2 as DynamicLayerNodes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x44ynamicNodes.proto\x1a\x17\x44ynamicLayerNodes.proto\"1\n\x0c\x44ynamicNodes\x12!\n\x05nodes\x18\x04 \x03(\x0b\x32\x12.DynamicLayerNodesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DynamicNodes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DYNAMICNODES._serialized_start=47
  _DYNAMICNODES._serialized_end=96
# @@protoc_insertion_point(module_scope)
