# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EffigyDailyInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45\x66\x66igyDailyInfo.proto\"\xc7\x01\n\x0f\x45\x66\x66igyDailyInfo\x12\x1b\n\x13\x63hallenge_max_score\x18\x06 \x01(\r\x12\"\n\x1ais_first_pass_reward_taken\x18\x0c \x01(\x08\x12\x1d\n\x15\x63hallenge_total_score\x18\x0f \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\x01 \x01(\r\x12\x17\n\x0f\x63hallenge_count\x18\x03 \x01(\r\x12\x11\n\tday_index\x18\x0e \x01(\r\x12\x12\n\nbegin_time\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EffigyDailyInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EFFIGYDAILYINFO._serialized_start=26
  _EFFIGYDAILYINFO._serialized_end=225
# @@protoc_insertion_point(module_scope)
