# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EffigyChallengeDungeonResultInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&EffigyChallengeDungeonResultInfo.proto\"\x9c\x01\n EffigyChallengeDungeonResultInfo\x12\x17\n\x0f\x63hallenge_score\x18\x0c \x01(\r\x12\x1b\n\x13\x63hallenge_max_score\x18\x08 \x01(\r\x12\x12\n\nis_success\x18\x02 \x01(\x08\x12\x18\n\x10is_in_time_limit\x18\x01 \x01(\x08\x12\x14\n\x0c\x63hallenge_id\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EffigyChallengeDungeonResultInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EFFIGYCHALLENGEDUNGEONRESULTINFO._serialized_start=43
  _EFFIGYCHALLENGEDUNGEONRESULTINFO._serialized_end=199
# @@protoc_insertion_point(module_scope)
