# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EffigyChallengeV2LevelData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n EffigyChallengeV2LevelData.proto\"\xb9\x01\n\x1a\x45\x66\x66igyChallengeV2LevelData\x12\x1b\n\x13Unk3300_PPOEMEILBIA\x18\r \x01(\r\x12\x15\n\ris_level_open\x18\x04 \x01(\x08\x12\x1b\n\x13Unk3300_KJEOADDMJMI\x18\t \x01(\r\x12\x1b\n\x13Unk3300_JMGACODMJLG\x18\x02 \x01(\r\x12\x1b\n\x13Unk3300_IJAGOAKOABH\x18\x07 \x01(\r\x12\x10\n\x08level_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EffigyChallengeV2LevelData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EFFIGYCHALLENGEV2LEVELDATA._serialized_start=37
  _EFFIGYCHALLENGEV2LEVELDATA._serialized_end=222
# @@protoc_insertion_point(module_scope)
