# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ElementReliquaryResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_GBBDJMDIDEI_pb2 as Unk2700__GBBDJMDIDEI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x45lementReliquaryResponse.proto\x1a\x19Unk2700_GBBDJMDIDEI.proto\"w\n\x18\x45lementReliquaryResponse\x12\x14\n\x0c\x65lement_type\x18\x0b \x01(\r\x12\x31\n\x13Unk2700_DMDHDIHGPFA\x18\x05 \x03(\x0b\x32\x14.Unk2700_GBBDJMDIDEI\x12\x12\n\nequip_type\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ElementReliquaryResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELEMENTRELIQUARYRESPONSE._serialized_start=61
  _ELEMENTRELIQUARYRESPONSE._serialized_end=180
# @@protoc_insertion_point(module_scope)
