# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntityRendererChangedInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x45ntityRendererChangedInfo.proto\"\xce\x01\n\x19\x45ntityRendererChangedInfo\x12K\n\x11\x63hanged_renderers\x18\x01 \x03(\x0b\x32\x30.EntityRendererChangedInfo.ChangedRenderersEntry\x12\x18\n\x10visibility_count\x18\x02 \x01(\r\x12\x11\n\tis_cached\x18\x03 \x01(\x08\x1a\x37\n\x15\x43hangedRenderersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EntityRendererChangedInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENTITYRENDERERCHANGEDINFO_CHANGEDRENDERERSENTRY._options = None
  _ENTITYRENDERERCHANGEDINFO_CHANGEDRENDERERSENTRY._serialized_options = b'8\001'
  _ENTITYRENDERERCHANGEDINFO._serialized_start=36
  _ENTITYRENDERERCHANGEDINFO._serialized_end=242
  _ENTITYRENDERERCHANGEDINFO_CHANGEDRENDERERSENTRY._serialized_start=187
  _ENTITYRENDERERCHANGEDINFO_CHANGEDRENDERERSENTRY._serialized_end=242
# @@protoc_insertion_point(module_scope)
