# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtAvatarEnterFocusNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ForwardType_pb2 as ForwardType__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x45vtAvatarEnterFocusNotify.proto\x1a\x11\x46orwardType.proto\x1a\x0cVector.proto\"\xed\x02\n\x19\x45vtAvatarEnterFocusNotify\x12\x11\n\tentity_id\x18\x01 \x01(\r\x12\x10\n\x08\x63\x61n_move\x18\n \x01(\x08\x12!\n\x19\x65nter_holding_focus_shoot\x18\r \x01(\x08\x12\x1b\n\x13Unk2700_GACKGHEHEIK\x18\x06 \x01(\x08\x12\x16\n\x0euse_auto_focus\x18\x05 \x01(\x08\x12\x12\n\nfast_focus\x18\x03 \x01(\x08\x12\x17\n\x0fshow_cross_hair\x18\x0c \x01(\x08\x12 \n\x18\x65nter_normal_focus_shoot\x18\x0e \x01(\x08\x12\"\n\x0c\x66orward_type\x18\x08 \x01(\x0e\x32\x0c.ForwardType\x12\x1e\n\rfocus_forward\x18\x07 \x01(\x0b\x32\x07.Vector\x12\x14\n\x0c\x64isable_anim\x18\t \x01(\x08\x12\x18\n\x10use_focus_sticky\x18\x0f \x01(\x08\x12\x10\n\x08use_gyro\x18\x0b \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtAvatarEnterFocusNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVTAVATARENTERFOCUSNOTIFY._serialized_start=69
  _EVTAVATARENTERFOCUSNOTIFY._serialized_end=434
# @@protoc_insertion_point(module_scope)
