# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtBeingHitNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EvtBeingHitInfo_pb2 as EvtBeingHitInfo__pb2
import ForwardType_pb2 as ForwardType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x45vtBeingHitNotify.proto\x1a\x15\x45vtBeingHitInfo.proto\x1a\x11\x46orwardType.proto\"a\n\x11\x45vtBeingHitNotify\x12(\n\x0e\x62\x65ing_hit_info\x18\x0c \x01(\x0b\x32\x10.EvtBeingHitInfo\x12\"\n\x0c\x66orward_type\x18\x0b \x01(\x0e\x32\x0c.ForwardTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtBeingHitNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVTBEINGHITNOTIFY._serialized_start=69
  _EVTBEINGHITNOTIFY._serialized_end=166
# @@protoc_insertion_point(module_scope)
