# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtDoSkillSuccNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ForwardType_pb2 as ForwardType__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x45vtDoSkillSuccNotify.proto\x1a\x11\x46orwardType.proto\x1a\x0cVector.proto\"y\n\x14\x45vtDoSkillSuccNotify\x12\x11\n\tcaster_id\x18\x0f \x01(\r\x12\"\n\x0c\x66orward_type\x18\t \x01(\x0e\x32\x0c.ForwardType\x12\x10\n\x08skill_id\x18\x0e \x01(\r\x12\x18\n\x07\x66orward\x18\r \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtDoSkillSuccNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVTDOSKILLSUCCNOTIFY._serialized_start=63
  _EVTDOSKILLSUCCNOTIFY._serialized_end=184
# @@protoc_insertion_point(module_scope)
