# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FetterData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46\x65tterData.proto\"N\n\nFetterData\x12\x11\n\tfetter_id\x18\x01 \x01(\r\x12\x14\n\x0c\x66\x65tter_state\x18\x02 \x01(\r\x12\x17\n\x0f\x63ond_index_list\x18\x03 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FetterData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FETTERDATA._serialized_start=20
  _FETTERDATA._serialized_end=98
# @@protoc_insertion_point(module_scope)
