# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FleurFairFallSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FallSettleInfo_pb2 as FallSettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46leurFairFallSettleInfo.proto\x1a\x14\x46\x61llSettleInfo.proto\"V\n\x17\x46leurFairFallSettleInfo\x12$\n\x0bsettle_info\x18\x04 \x01(\x0b\x32\x0f.FallSettleInfo\x12\x15\n\ris_new_record\x18\n \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FleurFairFallSettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLEURFAIRFALLSETTLEINFO._serialized_start=55
  _FLEURFAIRFALLSETTLEINFO._serialized_end=141
# @@protoc_insertion_point(module_scope)
