# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FleurFairDungeonSectionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!FleurFairDungeonSectionInfo.proto\"U\n\x1b\x46leurFairDungeonSectionInfo\x12\x0f\n\x07is_open\x18\x06 \x01(\x08\x12\x12\n\nsection_id\x18\x0e \x01(\r\x12\x11\n\topen_time\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FleurFairDungeonSectionInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLEURFAIRDUNGEONSECTIONINFO._serialized_start=37
  _FLEURFAIRDUNGEONSECTIONINFO._serialized_end=122
# @@protoc_insertion_point(module_scope)
