# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FleurFairMusicRecord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x46leurFairMusicRecord.proto\"O\n\x14\x46leurFairMusicRecord\x12\x11\n\tmax_score\x18\x0b \x01(\r\x12\x11\n\tis_unlock\x18\n \x01(\x08\x12\x11\n\tmax_combo\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FleurFairMusicRecord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLEURFAIRMUSICRECORD._serialized_start=30
  _FLEURFAIRMUSICRECORD._serialized_end=109
# @@protoc_insertion_point(module_scope)
