# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FlightActivityRestartRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x46lightActivityRestartRsp.proto\"R\n\x18\x46lightActivityRestartRsp\x12\x10\n\x08group_id\x18\x0b \x01(\r\x12\x13\n\x0bschedule_id\x18\n \x01(\r\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FlightActivityRestartRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLIGHTACTIVITYRESTARTRSP._serialized_start=34
  _FLIGHTACTIVITYRESTARTRSP._serialized_end=116
# @@protoc_insertion_point(module_scope)
