# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterUseBackupFungusReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%FungusFighterUseBackupFungusReq.proto\"@\n\x1f\x46ungusFighterUseBackupFungusReq\x12\x1d\n\x15\x62\x61\x63kup_fungus_id_list\x18\x08 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterUseBackupFungusReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSFIGHTERUSEBACKUPFUNGUSREQ._serialized_start=41
  _FUNGUSFIGHTERUSEBACKUPFUNGUSREQ._serialized_end=105
# @@protoc_insertion_point(module_scope)
