# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusDetail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46ungusDetail.proto\"\x82\x01\n\x0c\x46ungusDetail\x12\x0f\n\x07name_id\x18\x08 \x01(\r\x12\x1b\n\x13Unk3300_EHNBDJPANKL\x18\x02 \x01(\r\x12\x11\n\tfungus_id\x18\x03 \x01(\r\x12\x14\n\x0cis_cultivate\x18\x07 \x01(\x08\x12\x1b\n\x13Unk3300_GCLBPDJDEDN\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusDetail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSDETAIL._serialized_start=23
  _FUNGUSDETAIL._serialized_end=153
# @@protoc_insertion_point(module_scope)
