# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterMonsterDetail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n FungusFighterMonsterDetail.proto\"\\\n\x1a\x46ungusFighterMonsterDetail\x12\x19\n\x11\x63ur_hp_percentage\x18\t \x01(\x02\x12\x10\n\x08is_alive\x18\n \x01(\x08\x12\x11\n\tfungus_id\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterMonsterDetail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSFIGHTERMONSTERDETAIL._serialized_start=36
  _FUNGUSFIGHTERMONSTERDETAIL._serialized_end=128
# @@protoc_insertion_point(module_scope)
