# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterUseBackupFungusRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%FungusFighterUseBackupFungusRsp.proto\"2\n\x1f\x46ungusFighterUseBackupFungusRsp\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterUseBackupFungusRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSFIGHTERUSEBACKUPFUNGUSRSP._serialized_start=41
  _FUNGUSFIGHTERUSEBACKUPFUNGUSRSP._serialized_end=91
# @@protoc_insertion_point(module_scope)
