# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FungusDetail_pb2 as FungusDetail__pb2
import FungusPlotStageDetail_pb2 as FungusPlotStageDetail__pb2
import FungusTrainingDungeonDetail_pb2 as FungusTrainingDungeonDetail__pb2
import FungusTrainingProgressDetail_pb2 as FungusTrainingProgressDetail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46ungusFighterDetailInfo.proto\x1a\x12\x46ungusDetail.proto\x1a\x1b\x46ungusPlotStageDetail.proto\x1a!FungusTrainingDungeonDetail.proto\x1a\"FungusTrainingProgressDetail.proto\"\xe5\x02\n\x17\x46ungusFighterDetailInfo\x12)\n\x12\x66ungus_detail_list\x18\x06 \x03(\x0b\x32\r.FungusDetail\x12\x1b\n\x13Unk3300_GIHAKKAJHDH\x18\x01 \x03(\r\x12\x1b\n\x13Unk3300_KGKFJJHFHAB\x18\x08 \x03(\r\x12L\n%training_dungeon_progress_detail_list\x18\x03 \x03(\x0b\x32\x1d.FungusTrainingProgressDetail\x12\x1b\n\x13Unk3300_HPDOJOBPFMJ\x18\t \x03(\r\x12\x36\n\x16plot_stage_detail_list\x18\x0b \x03(\x0b\x32\x16.FungusPlotStageDetail\x12\x42\n\x1ctraining_dungeon_detail_list\x18\x02 \x03(\x0b\x32\x1c.FungusTrainingDungeonDetailb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSFIGHTERDETAILINFO._serialized_start=154
  _FUNGUSFIGHTERDETAILINFO._serialized_end=511
# @@protoc_insertion_point(module_scope)
