# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterTrainingSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStopReason_pb2 as GalleryStopReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%FungusFighterTrainingSettleInfo.proto\x1a\x17GalleryStopReason.proto\"m\n\x1f\x46ungusFighterTrainingSettleInfo\x12\x11\n\tused_time\x18\r \x01(\r\x12\"\n\x06reason\x18\x04 \x01(\x0e\x32\x12.GalleryStopReason\x12\x13\n\x0btransaction\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterTrainingSettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNGUSFIGHTERTRAININGSETTLEINFO._serialized_start=66
  _FUNGUSFIGHTERTRAININGSETTLEINFO._serialized_end=175
# @@protoc_insertion_point(module_scope)
