# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FunitureMakeMakeInfoChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FurnitureMakeMakeInfo_pb2 as FurnitureMakeMakeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&FunitureMakeMakeInfoChangeNotify.proto\x1a\x1b\x46urnitureMakeMakeInfo.proto\"M\n FunitureMakeMakeInfoChangeNotify\x12)\n\tmake_info\x18\x01 \x01(\x0b\x32\x16.FurnitureMakeMakeInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FunitureMakeMakeInfoChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNITUREMAKEMAKEINFOCHANGENOTIFY._serialized_start=71
  _FUNITUREMAKEMAKEINFOCHANGENOTIFY._serialized_end=148
# @@protoc_insertion_point(module_scope)
