# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FurnitureMakeStartRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FurnitureMakeSlot_pb2 as FurnitureMakeSlot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x46urnitureMakeStartRsp.proto\x1a\x17\x46urnitureMakeSlot.proto\"Y\n\x15\x46urnitureMakeStartRsp\x12/\n\x13\x66urniture_make_slot\x18\x05 \x01(\x0b\x32\x12.FurnitureMakeSlot\x12\x0f\n\x07retcode\x18\x08 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FurnitureMakeStartRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FURNITUREMAKESTARTRSP._serialized_start=56
  _FURNITUREMAKESTARTRSP._serialized_end=145
# @@protoc_insertion_point(module_scope)
