# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GachaActivityPercentNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GachaActivityPercentNotify.proto\"\xef\x01\n\x1aGachaActivityPercentNotify\x12\x1b\n\x13Unk3300_GHHIGKFDONE\x18\r \x01(\r\x12\x1b\n\x13Unk3300_EOPJBPHFDEE\x18\x06 \x01(\r\x12\x1b\n\x13Unk3300_IOLPAJKDEEA\x18\x05 \x01(\r\x12\x45\n\x0etarget_num_map\x18\x0c \x03(\x0b\x32-.GachaActivityPercentNotify.TargetNumMapEntry\x1a\x33\n\x11TargetNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaActivityPercentNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GACHAACTIVITYPERCENTNOTIFY_TARGETNUMMAPENTRY._options = None
  _GACHAACTIVITYPERCENTNOTIFY_TARGETNUMMAPENTRY._serialized_options = b'8\001'
  _GACHAACTIVITYPERCENTNOTIFY._serialized_start=37
  _GACHAACTIVITYPERCENTNOTIFY._serialized_end=276
  _GACHAACTIVITYPERCENTNOTIFY_TARGETNUMMAPENTRY._serialized_start=225
  _GACHAACTIVITYPERCENTNOTIFY_TARGETNUMMAPENTRY._serialized_end=276
# @@protoc_insertion_point(module_scope)
