# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GachaItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GachaTransferItem_pb2 as GachaTransferItem__pb2
import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGachaItem.proto\x1a\x17GachaTransferItem.proto\x1a\x0fItemParam.proto\"\xb6\x01\n\tGachaItem\x12\x1b\n\x13Unk3300_BGIOJBJFMFL\x18\x08 \x01(\x08\x12*\n\x0etransfer_items\x18\x06 \x03(\x0b\x32\x12.GachaTransferItem\x12\x1b\n\x13Unk3300_JNOOHBNJFIE\x18\r \x01(\x08\x12\x1e\n\ngacha_item\x18\x05 \x01(\x0b\x32\n.ItemParam\x12#\n\x0ftoken_item_list\x18\n \x03(\x0b\x32\n.ItemParamb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GACHAITEM._serialized_start=62
  _GACHAITEM._serialized_end=244
# @@protoc_insertion_point(module_scope)
