# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GadgetCustomTreeInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CustomGadgetTreeInfo_pb2 as CustomGadgetTreeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GadgetCustomTreeInfoNotify.proto\x1a\x1a\x43ustomGadgetTreeInfo.proto\"n\n\x1aGadgetCustomTreeInfoNotify\x12\x36\n\x17\x63ustom_gadget_tree_info\x18\x05 \x01(\x0b\x32\x15.CustomGadgetTreeInfo\x12\x18\n\x10gadget_entity_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GadgetCustomTreeInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GADGETCUSTOMTREEINFONOTIFY._serialized_start=64
  _GADGETCUSTOMTREEINFONOTIFY._serialized_end=174
# @@protoc_insertion_point(module_scope)
