# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GadgetPlayInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GadgetCrucibleInfo_pb2 as GadgetCrucibleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14GadgetPlayInfo.proto\x1a\x18GadgetCrucibleInfo.proto\"\xc5\x01\n\x0eGadgetPlayInfo\x12\x11\n\tplay_type\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\x12\x1b\n\x13progress_stage_list\x18\x03 \x03(\r\x12\x10\n\x08start_cd\x18\x04 \x01(\r\x12\x12\n\nstart_time\x18\x05 \x01(\r\x12\x10\n\x08progress\x18\x06 \x01(\r\x12,\n\rcrucible_info\x18\x15 \x01(\x0b\x32\x13.GadgetCrucibleInfoH\x00\x42\x0b\n\tplay_infob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GadgetPlayInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GADGETPLAYINFO._serialized_start=51
  _GADGETPLAYINFO._serialized_end=248
# @@protoc_insertion_point(module_scope)
