# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GallerySumoKillMonsterNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GallerySumoKillMonsterNotify.proto\"\x82\x01\n\x1cGallerySumoKillMonsterNotify\x12\x1f\n\x17kill_normal_mosnter_num\x18\x04 \x01(\r\x12\r\n\x05score\x18\x07 \x01(\r\x12\x1e\n\x16kill_elite_monster_num\x18\x0e \x01(\r\x12\x12\n\ngallery_id\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GallerySumoKillMonsterNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALLERYSUMOKILLMONSTERNOTIFY._serialized_start=39
  _GALLERYSUMOKILLMONSTERNOTIFY._serialized_end=169
# @@protoc_insertion_point(module_scope)
