# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GalleryWillStartCountdownNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStartSource_pb2 as GalleryStartSource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%GalleryWillStartCountdownNotify.proto\x1a\x18GalleryStartSource.proto\"\x82\x01\n\x1fGalleryWillStartCountdownNotify\x12\x12\n\ngallery_id\x18\r \x01(\r\x12)\n\x0cstart_source\x18\x0e \x01(\x0e\x32\x13.GalleryStartSource\x12\x10\n\x08\x65nd_time\x18\x0f \x01(\r\x12\x0e\n\x06is_end\x18\x06 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GalleryWillStartCountdownNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALLERYWILLSTARTCOUNTDOWNNOTIFY._serialized_start=68
  _GALLERYWILLSTARTCOUNTDOWNNOTIFY._serialized_end=198
# @@protoc_insertion_point(module_scope)
