# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameplayRecommendationReliquaryResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GameplayRecommendationReliquaryMainPropData_pb2 as GameplayRecommendationReliquaryMainPropData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-GameplayRecommendationReliquaryResponse.proto\x1a\x31GameplayRecommendationReliquaryMainPropData.proto\"\x88\x01\n\'GameplayRecommendationReliquaryResponse\x12\x12\n\nequip_type\x18\x0b \x01(\r\x12I\n\x13main_prop_data_list\x18\x02 \x03(\x0b\x32,.GameplayRecommendationReliquaryMainPropDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameplayRecommendationReliquaryResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEPLAYRECOMMENDATIONRELIQUARYRESPONSE._serialized_start=101
  _GAMEPLAYRECOMMENDATIONRELIQUARYRESPONSE._serialized_end=237
# @@protoc_insertion_point(module_scope)
