# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGBossChallengeUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGBossChallengeData_pb2 as GCGBossChallengeData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GCGBossChallengeUpdateNotify.proto\x1a\x1aGCGBossChallengeData.proto\"M\n\x1cGCGBossChallengeUpdateNotify\x12-\n\x0e\x62oss_challenge\x18\x07 \x01(\x0b\x32\x15.GCGBossChallengeDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGBossChallengeUpdateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGBOSSCHALLENGEUPDATENOTIFY._serialized_start=66
  _GCGBOSSCHALLENGEUPDATENOTIFY._serialized_end=143
# @@protoc_insertion_point(module_scope)
