# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGControllerShowInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ProfilePicture_pb2 as ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bGCGControllerShowInfo.proto\x1a\x14ProfilePicture.proto\"\x8e\x01\n\x15GCGControllerShowInfo\x12\x0e\n\x06psn_id\x18\x0c \x01(\t\x12\x11\n\tnick_name\x18\n \x01(\t\x12\x11\n\tonline_id\x18\x0f \x01(\t\x12(\n\x0fprofile_picture\x18\x03 \x01(\x0b\x32\x0f.ProfilePicture\x12\x15\n\rcontroller_id\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGControllerShowInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGCONTROLLERSHOWINFO._serialized_start=54
  _GCGCONTROLLERSHOWINFO._serialized_end=196
# @@protoc_insertion_point(module_scope)
