# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGIntentionChangeType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGCGIntentionChangeType.proto*^\n\x16GCGIntentionChangeType\x12\"\n\x1eGCG_INTENTION_CHANGE_TYPE_NONE\x10\x00\x12 \n\x1cGCG_INTENTION_CHANGE_TYPE_RM\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGIntentionChangeType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGINTENTIONCHANGETYPE._serialized_start=32
  _GCGINTENTIONCHANGETYPE._serialized_end=126
# @@protoc_insertion_point(module_scope)
