# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGLevelChallengeDeleteNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#GCGLevelChallengeDeleteNotify.proto\"6\n\x1dGCGLevelChallengeDeleteNotify\x12\x15\n\rlevel_id_list\x18\x06 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGLevelChallengeDeleteNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGLEVELCHALLENGEDELETENOTIFY._serialized_start=39
  _GCGLEVELCHALLENGEDELETENOTIFY._serialized_end=93
# @@protoc_insertion_point(module_scope)
