# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGMsgAddDice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGDiceSideType_pb2 as GCGDiceSideType__pb2
import GCGReason_pb2 as GCGReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GCGMsgAddDice.proto\x1a\x15GCGDiceSideType.proto\x1a\x0fGCGReason.proto\"\xfc\x02\n\rGCGMsgAddDice\x12\x43\n\x13Unk3300_KFKOGOKPIFN\x18\r \x03(\x0b\x32&.GCGMsgAddDice.Unk3300KFKOGOKPIFNEntry\x12\x1a\n\x06reason\x18\n \x01(\x0e\x32\n.GCGReason\x12\x14\n\x0c\x63hange_count\x18\x06 \x01(\x05\x12\x43\n\x13Unk3300_PCMPCCLFEIM\x18\x0b \x03(\x0b\x32&.GCGMsgAddDice.Unk3300PCMPCCLFEIMEntry\x12\x15\n\rcontroller_id\x18\x05 \x01(\r\x1aK\n\x17Unk3300KFKOGOKPIFNEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0e\x32\x10.GCGDiceSideType:\x02\x38\x01\x1aK\n\x17Unk3300PCMPCCLFEIMEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0e\x32\x10.GCGDiceSideType:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGMsgAddDice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGMSGADDDICE_UNK3300KFKOGOKPIFNENTRY._options = None
  _GCGMSGADDDICE_UNK3300KFKOGOKPIFNENTRY._serialized_options = b'8\001'
  _GCGMSGADDDICE_UNK3300PCMPCCLFEIMENTRY._options = None
  _GCGMSGADDDICE_UNK3300PCMPCCLFEIMENTRY._serialized_options = b'8\001'
  _GCGMSGADDDICE._serialized_start=64
  _GCGMSGADDDICE._serialized_end=444
  _GCGMSGADDDICE_UNK3300KFKOGOKPIFNENTRY._serialized_start=292
  _GCGMSGADDDICE_UNK3300KFKOGOKPIFNENTRY._serialized_end=367
  _GCGMSGADDDICE_UNK3300PCMPCCLFEIMENTRY._serialized_start=369
  _GCGMSGADDDICE_UNK3300PCMPCCLFEIMENTRY._serialized_end=444
# @@protoc_insertion_point(module_scope)
