# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGCGReason.proto*\xd8\x02\n\tGCGReason\x12\x16\n\x12GCG_REASON_DEFAULT\x10\x00\x12\x15\n\x11GCG_REASON_EFFECT\x10\x01\x12\x13\n\x0fGCG_REASON_COST\x10\x02\x12\x11\n\rGCG_REASON_GM\x10\x03\x12\x15\n\x11GCG_REASON_ATTACK\x10\x04\x12\x15\n\x11GCG_REASON_REBOOT\x10\x05\x12\x18\n\x14GCG_REASON_PLAY_CARD\x10\x06\x12\x1e\n\x1aGCG_REASON_QUICKLY_ONSTAGE\x10\x07\x12\x1f\n\x1bGCG_REASON_REMOVE_AFTER_DIE\x10\x08\x12\x13\n\x0fGCG_REASON_INIT\x10\t\x12\x1c\n\x18GCG_REASON_EFFECT_DAMAGE\x10\n\x12\x1a\n\x16GCG_REASON_EFFECT_HEAL\x10\x0b\x12\x1c\n\x18GCG_REASON_EFFECT_REVIVE\x10\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGReason_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGREASON._serialized_start=20
  _GCGREASON._serialized_end=364
# @@protoc_insertion_point(module_scope)
