# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGSkillPreviewHpInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGSkillHpChangeType_pb2 as GCGSkillHpChangeType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bGCGSkillPreviewHpInfo.proto\x1a\x1aGCGSkillHpChangeType.proto\"\\\n\x15GCGSkillPreviewHpInfo\x12*\n\x0b\x63hange_type\x18\x08 \x01(\x0e\x32\x15.GCGSkillHpChangeType\x12\x17\n\x0fhp_change_value\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGSkillPreviewHpInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGSKILLPREVIEWHPINFO._serialized_start=59
  _GCGSKILLPREVIEWHPINFO._serialized_end=151
# @@protoc_insertion_point(module_scope)
