# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGSettleOption.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15GCGSettleOption.proto*\x98\x01\n\x0fGCGSettleOption\x12\x1e\n\x1aGCG_SETTLE_OPTION_OPT_NONE\x10\x00\x12\x1e\n\x1aGCG_SETTLE_OPTION_OPT_EXIT\x10\x01\x12\"\n\x1eGCG_SETTLE_OPTION_OPT_CONTINUE\x10\x02\x12!\n\x1dGCG_SETTLE_OPTION_OPT_RESTART\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGSettleOption_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCGSETTLEOPTION._serialized_start=26
  _GCGSETTLEOPTION._serialized_end=178
# @@protoc_insertion_point(module_scope)
