# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GearActivityFinishPlayGearReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GearColumnInfo_pb2 as GearColumnInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#GearActivityFinishPlayGearReq.proto\x1a\x14GearColumnInfo.proto\"\x87\x01\n\x1dGearActivityFinishPlayGearReq\x12\x10\n\x08use_clue\x18\n \x01(\x08\x12\x10\n\x08level_id\x18\x03 \x01(\r\x12\x12\n\nis_success\x18\x08 \x01(\x08\x12.\n\x15gear_column_info_list\x18\x0c \x03(\x0b\x32\x0f.GearColumnInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GearActivityFinishPlayGearReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARACTIVITYFINISHPLAYGEARREQ._serialized_start=62
  _GEARACTIVITYFINISHPLAYGEARREQ._serialized_end=197
# @@protoc_insertion_point(module_scope)
