# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GearActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GearLevelData_pb2 as GearLevelData__pb2
import JigsawPictureData_pb2 as JigsawPictureData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGearActivityDetailInfo.proto\x1a\x13GearLevelData.proto\x1a\x17JigsawPictureData.proto\"w\n\x16GearActivityDetailInfo\x12,\n\x14gear_level_data_list\x18\x02 \x03(\x0b\x32\x0e.GearLevelData\x12/\n\x13jigsaw_picture_data\x18\x08 \x01(\x0b\x32\x12.JigsawPictureDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GearActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARACTIVITYDETAILINFO._serialized_start=78
  _GEARACTIVITYDETAILINFO._serialized_end=197
# @@protoc_insertion_point(module_scope)
