# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetActivityScheduleRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityScheduleInfo_pb2 as ActivityScheduleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetActivityScheduleRsp.proto\x1a\x1a\x41\x63tivityScheduleInfo.proto\"\x81\x01\n\x16GetActivityScheduleRsp\x12\x35\n\x16\x61\x63tivity_schedule_list\x18\t \x03(\x0b\x32\x15.ActivityScheduleInfo\x12\x0f\n\x07retcode\x18\r \x01(\x05\x12\x1f\n\x17remain_fly_sea_lamp_num\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetActivityScheduleRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETACTIVITYSCHEDULERSP._serialized_start=61
  _GETACTIVITYSCHEDULERSP._serialized_end=190
# @@protoc_insertion_point(module_scope)
