# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetAllSceneGalleryInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneGalleryInfo_pb2 as SceneGalleryInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGetAllSceneGalleryInfoRsp.proto\x1a\x16SceneGalleryInfo.proto\"Z\n\x19GetAllSceneGalleryInfoRsp\x12,\n\x11gallery_info_list\x18\x0c \x03(\x0b\x32\x11.SceneGalleryInfo\x12\x0f\n\x07retcode\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetAllSceneGalleryInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETALLSCENEGALLERYINFORSP._serialized_start=59
  _GETALLSCENEGALLERYINFORSP._serialized_end=149
# @@protoc_insertion_point(module_scope)
