# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetCityReputationInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CityReputationInfo_pb2 as CityReputationInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGetCityReputationInfoRsp.proto\x1a\x18\x43ityReputationInfo.proto\"o\n\x18GetCityReputationInfoRsp\x12\x0f\n\x07\x63ity_id\x18\x01 \x01(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x12\x31\n\x14\x63ity_reputation_info\x18\t \x01(\x0b\x32\x13.CityReputationInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetCityReputationInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCITYREPUTATIONINFORSP._serialized_start=60
  _GETCITYREPUTATIONINFORSP._serialized_end=171
# @@protoc_insertion_point(module_scope)
