# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFriendShowNameCardInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GetFriendShowNameCardInfoRsp.proto\"\\\n\x1cGetFriendShowNameCardInfoRsp\x12\x1e\n\x16show_name_card_id_list\x18\x05 \x03(\r\x12\x0b\n\x03uid\x18\t \x01(\r\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriendShowNameCardInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETFRIENDSHOWNAMECARDINFORSP._serialized_start=38
  _GETFRIENDSHOWNAMECARDINFORSP._serialized_end=130
# @@protoc_insertion_point(module_scope)
