# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetInvestigationMonsterReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GetInvestigationMonsterReq.proto\"O\n\x1aGetInvestigationMonsterReq\x12\x14\n\x0c\x63ity_id_list\x18\x03 \x03(\r\x12\x1b\n\x13Unk2700_DEMFDHNFBBJ\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetInvestigationMonsterReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINVESTIGATIONMONSTERREQ._serialized_start=36
  _GETINVESTIGATIONMONSTERREQ._serialized_end=115
# @@protoc_insertion_point(module_scope)
