# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetInvestigationMonsterRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import InvestigationMonster_pb2 as InvestigationMonster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GetInvestigationMonsterRsp.proto\x1a\x1aInvestigationMonster.proto\"w\n\x1aGetInvestigationMonsterRsp\x12+\n\x0cmonster_list\x18\n \x03(\x0b\x32\x15.InvestigationMonster\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x1b\n\x13Unk2700_DEMFDHNFBBJ\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetInvestigationMonsterRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINVESTIGATIONMONSTERRSP._serialized_start=64
  _GETINVESTIGATIONMONSTERRSP._serialized_end=183
# @@protoc_insertion_point(module_scope)
