# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetMechanicusInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MechanicusInfo_pb2 as MechanicusInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetMechanicusInfoRsp.proto\x1a\x14MechanicusInfo.proto\"Q\n\x14GetMechanicusInfoRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x12(\n\x0fmechanicus_info\x18\x0f \x01(\x0b\x32\x0f.MechanicusInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetMechanicusInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMECHANICUSINFORSP._serialized_start=52
  _GETMECHANICUSINFORSP._serialized_end=133
# @@protoc_insertion_point(module_scope)
