# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPlayerMpModeAvailabilityRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$GetPlayerMpModeAvailabilityRsp.proto\"U\n\x1eGetPlayerMpModeAvailabilityRsp\x12\x12\n\nparam_list\x18\x08 \x03(\r\x12\x0e\n\x06mp_ret\x18\x0c \x01(\x05\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetPlayerMpModeAvailabilityRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPLAYERMPMODEAVAILABILITYRSP._serialized_start=40
  _GETPLAYERMPMODEAVAILABILITYRSP._serialized_end=125
# @@protoc_insertion_point(module_scope)
