# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRecommendCustomDungeonRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import OtherCustomDungeonBrief_pb2 as OtherCustomDungeonBrief__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GetRecommendCustomDungeonRsp.proto\x1a\x1dOtherCustomDungeonBrief.proto\"f\n\x1cGetRecommendCustomDungeonRsp\x12\x35\n\x13\x63ustom_dungeon_list\x18\x07 \x03(\x0b\x32\x18.OtherCustomDungeonBrief\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRecommendCustomDungeonRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETRECOMMENDCUSTOMDUNGEONRSP._serialized_start=69
  _GETRECOMMENDCUSTOMDUNGEONRSP._serialized_end=171
# @@protoc_insertion_point(module_scope)
