# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetScenePerformanceRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetScenePerformanceRsp.proto\x1a\x0cVector.proto\"\xda\x01\n\x16GetScenePerformanceRsp\x12\x13\n\x0bmonster_num\x18\t \x01(\r\x12\x1a\n\x12gather_num_insight\x18\x01 \x01(\r\x12\x12\n\ngadget_num\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x12\x19\n\x11\x64ynamic_group_num\x18\x0c \x01(\r\x12\x11\n\tgroup_num\x18\x02 \x01(\r\x12\x14\n\x03pos\x18\x04 \x01(\x0b\x32\x07.Vector\x12\x12\n\nentity_num\x18\x08 \x01(\r\x12\x12\n\ngather_num\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetScenePerformanceRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSCENEPERFORMANCERSP._serialized_start=47
  _GETSCENEPERFORMANCERSP._serialized_end=265
# @@protoc_insertion_point(module_scope)
