# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetSceneNpcPositionRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NpcPositionInfo_pb2 as NpcPositionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetSceneNpcPositionRsp.proto\x1a\x15NpcPositionInfo.proto\"d\n\x16GetSceneNpcPositionRsp\x12\x10\n\x08scene_id\x18\x01 \x01(\r\x12\'\n\rnpc_info_list\x18\x02 \x03(\x0b\x32\x10.NpcPositionInfo\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetSceneNpcPositionRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSCENENPCPOSITIONRSP._serialized_start=55
  _GETSCENENPCPOSITIONRSP._serialized_end=155
# @@protoc_insertion_point(module_scope)
