# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GlobalBuildingInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BuildingInfo_pb2 as BuildingInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGlobalBuildingInfoNotify.proto\x1a\x12\x42uildingInfo.proto\"f\n\x18GlobalBuildingInfoNotify\x12\x0f\n\x07max_num\x18\x01 \x01(\r\x12\x13\n\x0b\x63urrent_num\x18\x03 \x01(\r\x12$\n\rbuilding_list\x18\x0f \x03(\x0b\x32\r.BuildingInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GlobalBuildingInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GLOBALBUILDINGINFONOTIFY._serialized_start=54
  _GLOBALBUILDINGINFONOTIFY._serialized_end=156
# @@protoc_insertion_point(module_scope)
