# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GMShowObstacleRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GMObstacleInfo_pb2 as GMObstacleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GMShowObstacleRsp.proto\x1a\x14GMObstacleInfo.proto\"H\n\x11GMShowObstacleRsp\x12\"\n\tobstacles\x18\x08 \x03(\x0b\x32\x0f.GMObstacleInfo\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GMShowObstacleRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GMSHOWOBSTACLERSP._serialized_start=49
  _GMSHOWOBSTACLERSP._serialized_end=121
# @@protoc_insertion_point(module_scope)
