# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GravenInnocenceCampStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GravenInnocenceCampStageInfo.proto\"h\n\x1cGravenInnocenceCampStageInfo\x12\x0f\n\x07is_open\x18\x0b \x01(\x08\x12\x13\n\x0bis_finished\x18\x06 \x01(\x08\x12\x10\n\x08level_id\x18\x07 \x01(\r\x12\x10\n\x08stage_id\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GravenInnocenceCampStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRAVENINNOCENCECAMPSTAGEINFO._serialized_start=38
  _GRAVENINNOCENCECAMPSTAGEINFO._serialized_end=142
# @@protoc_insertion_point(module_scope)
