# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GravenInnocenceRaceSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStopReason_pb2 as GalleryStopReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%GravenInnocenceRaceSettleNotify.proto\x1a\x17GalleryStopReason.proto\"\x91\x02\n\x1fGravenInnocenceRaceSettleNotify\x12\x12\n\ngallery_id\x18\t \x01(\r\x12\x15\n\ris_new_record\x18\x03 \x01(\x08\x12\x10\n\x08level_id\x18\x0b \x01(\r\x12\x1b\n\x13Unk3300_BOIPHOPMHJM\x18\x08 \x01(\r\x12\r\n\x05score\x18\x04 \x01(\r\x12\x12\n\nis_success\x18\n \x01(\x08\x12\"\n\x06reason\x18\x0c \x01(\x0e\x32\x12.GalleryStopReason\x12\x1b\n\x13Unk3300_IPGJKKFDPJJ\x18\x06 \x01(\r\x12\x13\n\x0bremain_time\x18\x02 \x01(\r\x12\x1b\n\x13Unk3300_OHAHHKNAJKL\x18\x07 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GravenInnocenceRaceSettleNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRAVENINNOCENCERACESETTLENOTIFY._serialized_start=67
  _GRAVENINNOCENCERACESETTLENOTIFY._serialized_end=340
# @@protoc_insertion_point(module_scope)
