# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSuiteNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GroupSuiteNotify.proto\"w\n\x10GroupSuiteNotify\x12\x32\n\tgroup_map\x18\x03 \x03(\x0b\x32\x1f.GroupSuiteNotify.GroupMapEntry\x1a/\n\rGroupMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupSuiteNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPSUITENOTIFY_GROUPMAPENTRY._options = None
  _GROUPSUITENOTIFY_GROUPMAPENTRY._serialized_options = b'8\001'
  _GROUPSUITENOTIFY._serialized_start=26
  _GROUPSUITENOTIFY._serialized_end=145
  _GROUPSUITENOTIFY_GROUPMAPENTRY._serialized_start=98
  _GROUPSUITENOTIFY_GROUPMAPENTRY._serialized_end=145
# @@protoc_insertion_point(module_scope)
