# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupLinkAllNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GroupLinkBundle_pb2 as GroupLinkBundle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GroupLinkAllNotify.proto\x1a\x15GroupLinkBundle.proto\";\n\x12GroupLinkAllNotify\x12%\n\x0b\x62undle_list\x18\t \x03(\x0b\x32\x10.GroupLinkBundleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupLinkAllNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPLINKALLNOTIFY._serialized_start=51
  _GROUPLINKALLNOTIFY._serialized_end=110
# @@protoc_insertion_point(module_scope)
