# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HideAndSeekActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_LBOAEFMECCP_pb2 as Unk2700__LBOAEFMECCP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#HideAndSeekActivityDetailInfo.proto\x1a\x19Unk2700_LBOAEFMECCP.proto\"\xae\x01\n\x1dHideAndSeekActivityDetailInfo\x12\x31\n\x13Unk2700_JDMDOOHFNCA\x18\x01 \x03(\x0b\x32\x14.Unk2700_LBOAEFMECCP\x12 \n\x18\x63hosen_hunter_skill_list\x18\x04 \x03(\r\x12\x17\n\x0funlock_map_list\x18\r \x03(\r\x12\x1f\n\x17\x63hosen_hider_skill_list\x18\x06 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HideAndSeekActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HIDEANDSEEKACTIVITYDETAILINFO._serialized_start=67
  _HIDEANDSEEKACTIVITYDETAILINFO._serialized_end=241
# @@protoc_insertion_point(module_scope)
