# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeMarkPointSceneData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeMarkPointFurnitureData_pb2 as HomeMarkPointFurnitureData__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cHomeMarkPointSceneData.proto\x1a HomeMarkPointFurnitureData.proto\x1a\x0cVector.proto\"\xbe\x01\n\x16HomeMarkPointSceneData\x12$\n\x13Unk3300_ONJJJEPFKJI\x18\t \x01(\x0b\x32\x07.Vector\x12\x10\n\x08scene_id\x18\x06 \x01(\r\x12$\n\x13Unk3300_HFNOINGPMJP\x18\x0b \x01(\x0b\x32\x07.Vector\x12\x11\n\tmodule_id\x18\x08 \x01(\r\x12\x33\n\x0e\x66urniture_list\x18\r \x03(\x0b\x32\x1b.HomeMarkPointFurnitureDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeMarkPointSceneData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEMARKPOINTSCENEDATA._serialized_start=81
  _HOMEMARKPOINTSCENEDATA._serialized_end=271
# @@protoc_insertion_point(module_scope)
