# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeResourceNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeResource_pb2 as HomeResource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18HomeResourceNotify.proto\x1a\x12HomeResource.proto\"Y\n\x12HomeResourceNotify\x12!\n\nfetter_exp\x18\x07 \x01(\x0b\x32\r.HomeResource\x12 \n\thome_coin\x18\x05 \x01(\x0b\x32\r.HomeResourceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeResourceNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMERESOURCENOTIFY._serialized_start=48
  _HOMERESOURCENOTIFY._serialized_end=137
# @@protoc_insertion_point(module_scope)
