# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeCreateBlueprintReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeSceneArrangementInfo_pb2 as HomeSceneArrangementInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cHomeCreateBlueprintReq.proto\x1a\x1eHomeSceneArrangementInfo.proto\"\x9d\x01\n\x16HomeCreateBlueprintReq\x12\x39\n\x16scene_arrangement_info\x18\x04 \x01(\x0b\x32\x19.HomeSceneArrangementInfo\x12\x1c\n\x14gen_share_code_count\x18\t \x01(\r\x12\x19\n\x11server_share_code\x18\x05 \x01(\t\x12\x0f\n\x07slot_id\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeCreateBlueprintReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMECREATEBLUEPRINTREQ._serialized_start=65
  _HOMECREATEBLUEPRINTREQ._serialized_end=222
# @@protoc_insertion_point(module_scope)
