# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeFurnitureData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17HomeFurnitureData.proto\x1a\x0cVector.proto\"\xa0\x01\n\x11HomeFurnitureData\x12\x0f\n\x07version\x18\x06 \x01(\r\x12\x1e\n\x16parent_furniture_index\x18\x03 \x01(\x05\x12\x14\n\x0c\x66urniture_id\x18\x04 \x01(\r\x12\x0c\n\x04guid\x18\t \x01(\r\x12\x1a\n\tspawn_rot\x18\n \x01(\x0b\x32\x07.Vector\x12\x1a\n\tspawn_pos\x18\x08 \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeFurnitureData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEFURNITUREDATA._serialized_start=42
  _HOMEFURNITUREDATA._serialized_end=202
# @@protoc_insertion_point(module_scope)
