# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomePlantSeedReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16HomePlantSeedReq.proto\"K\n\x10HomePlantSeedReq\x12\x14\n\x0cseed_id_list\x18\x07 \x03(\r\x12\x12\n\nfield_guid\x18\x01 \x01(\r\x12\r\n\x05index\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomePlantSeedReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEPLANTSEEDREQ._serialized_start=26
  _HOMEPLANTSEEDREQ._serialized_end=101
# @@protoc_insertion_point(module_scope)
