# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeVerifyData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeSceneArrangementMuipData_pb2 as HomeSceneArrangementMuipData__pb2
import HomeVerifySceneData_pb2 as HomeVerifySceneData__pb2
import LanguageType_pb2 as LanguageType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14HomeVerifyData.proto\x1a\"HomeSceneArrangementMuipData.proto\x1a\x19HomeVerifySceneData.proto\x1a\x12LanguageType.proto\"\xdb\x01\n\x0eHomeVerifyData\x12\'\n\thome_info\x18\x04 \x01(\x0b\x32\x14.HomeVerifySceneData\x12\x37\n\x10\x61rrangement_data\x18\t \x01(\x0b\x32\x1d.HomeSceneArrangementMuipData\x12\x11\n\ttimestamp\x18\x0b \x01(\x07\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03\x61id\x18\n \x01(\t\x12\x1b\n\x04lang\x18\x06 \x01(\x0e\x32\r.LanguageType\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\x0e\n\x06region\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeVerifyData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEVERIFYDATA._serialized_start=108
  _HOMEVERIFYDATA._serialized_end=327
# @@protoc_insertion_point(module_scope)
