# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeSeekFurnitureGalleryScoreNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStopReason_pb2 as GalleryStopReason__pb2
import HomeSeekFurnitureOneRecord_pb2 as HomeSeekFurnitureOneRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)HomeSeekFurnitureGalleryScoreNotify.proto\x1a\x17GalleryStopReason.proto\x1a HomeSeekFurnitureOneRecord.proto\"\x8a\x01\n#HomeSeekFurnitureGalleryScoreNotify\x12\"\n\x06reason\x18\x07 \x01(\x0e\x32\x12.GalleryStopReason\x12\x12\n\ngallery_id\x18\r \x01(\r\x12+\n\x06record\x18\x02 \x01(\x0b\x32\x1b.HomeSeekFurnitureOneRecordb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeSeekFurnitureGalleryScoreNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMESEEKFURNITUREGALLERYSCORENOTIFY._serialized_start=105
  _HOMESEEKFURNITUREGALLERYSCORENOTIFY._serialized_end=243
# @@protoc_insertion_point(module_scope)
