# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeBlockDotPattern.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HomeBlockDotPattern.proto\"B\n\x13HomeBlockDotPattern\x12\r\n\x05width\x18\r \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x0c \x01(\x0c\x12\x0e\n\x06height\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeBlockDotPattern_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEBLOCKDOTPATTERN._serialized_start=29
  _HOMEBLOCKDOTPATTERN._serialized_end=95
# @@protoc_insertion_point(module_scope)
