# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeUpdatePictureFrameInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomePictureFrameInfo_pb2 as HomePictureFrameInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#HomeUpdatePictureFrameInfoRsp.proto\x1a\x1aHomePictureFrameInfo.proto\"c\n\x1dHomeUpdatePictureFrameInfoRsp\x12\x31\n\x12picture_frame_info\x18\x06 \x01(\x0b\x32\x15.HomePictureFrameInfo\x12\x0f\n\x07retcode\x18\t \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeUpdatePictureFrameInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEUPDATEPICTUREFRAMEINFORSP._serialized_start=67
  _HOMEUPDATEPICTUREFRAMEINFORSP._serialized_end=166
# @@protoc_insertion_point(module_scope)
