# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeUpdateFishFarmingInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"HomeUpdateFishFarmingInfoRsp.proto\"/\n\x1cHomeUpdateFishFarmingInfoRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeUpdateFishFarmingInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEUPDATEFISHFARMINGINFORSP._serialized_start=38
  _HOMEUPDATEFISHFARMINGINFORSP._serialized_end=85
# @@protoc_insertion_point(module_scope)
