# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeAvatarSummonEventInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fHomeAvatarSummonEventInfo.proto\"\x91\x01\n\x19HomeAvatarSummonEventInfo\x12\x17\n\x0frandom_position\x18\x0b \x01(\r\x12\x0c\n\x04guid\x18\x05 \x01(\r\x12\x17\n\x0f\x65vent_over_time\x18\x06 \x01(\r\x12\x0f\n\x07suit_id\x18\x0c \x01(\r\x12\x11\n\tavatar_id\x18\x08 \x01(\r\x12\x10\n\x08\x65vent_id\x18\n \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeAvatarSummonEventInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEAVATARSUMMONEVENTINFO._serialized_start=36
  _HOMEAVATARSUMMONEVENTINFO._serialized_end=181
# @@protoc_insertion_point(module_scope)
