# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeGetBlueprintSlotInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeBlueprintSlotInfo_pb2 as HomeBlueprintSlotInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!HomeGetBlueprintSlotInfoRsp.proto\x1a\x1bHomeBlueprintSlotInfo.proto\"{\n\x1bHomeGetBlueprintSlotInfoRsp\x12\x1b\n\x13\x64\x65lete_slot_id_list\x18\x01 \x03(\r\x12.\n\x0eslot_info_list\x18\x0f \x03(\x0b\x32\x16.HomeBlueprintSlotInfo\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeGetBlueprintSlotInfoRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEGETBLUEPRINTSLOTINFORSP._serialized_start=66
  _HOMEGETBLUEPRINTSLOTINFORSP._serialized_end=189
# @@protoc_insertion_point(module_scope)
