# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeFishFarmingInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeFishFarmingInfo_pb2 as HomeFishFarmingInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fHomeFishFarmingInfoNotify.proto\x1a\x19HomeFishFarmingInfo.proto\"Q\n\x19HomeFishFarmingInfoNotify\x12\x34\n\x16\x66ish_farming_info_list\x18\x0f \x03(\x0b\x32\x14.HomeFishFarmingInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeFishFarmingInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEFISHFARMINGINFONOTIFY._serialized_start=62
  _HOMEFISHFARMINGINFONOTIFY._serialized_end=143
# @@protoc_insertion_point(module_scope)
