# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeAvatarRewardEventInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fHomeAvatarRewardEventInfo.proto\"y\n\x19HomeAvatarRewardEventInfo\x12\x11\n\tavatar_id\x18\x01 \x01(\r\x12\x0c\n\x04guid\x18\x0c \x01(\r\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\r\x12\x10\n\x08suite_id\x18\x0e \x01(\r\x12\x17\n\x0frandom_position\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeAvatarRewardEventInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEAVATARREWARDEVENTINFO._serialized_start=35
  _HOMEAVATARREWARDEVENTINFO._serialized_end=156
# @@protoc_insertion_point(module_scope)
