# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeLimitedShopBuyGoodsRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeLimitedShopGoods_pb2 as HomeLimitedShopGoods__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n HomeLimitedShopBuyGoodsRsp.proto\x1a\x1aHomeLimitedShopGoods.proto\"\x91\x01\n\x1aHomeLimitedShopBuyGoodsRsp\x12)\n\ngoods_list\x18\x03 \x03(\x0b\x32\x15.HomeLimitedShopGoods\x12\x11\n\tbuy_count\x18\n \x01(\r\x12\x0f\n\x07retcode\x18\r \x01(\x05\x12$\n\x05goods\x18\t \x01(\x0b\x32\x15.HomeLimitedShopGoodsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeLimitedShopBuyGoodsRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMELIMITEDSHOPBUYGOODSRSP._serialized_start=65
  _HOMELIMITEDSHOPBUYGOODSRSP._serialized_end=210
# @@protoc_insertion_point(module_scope)
