# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeFurnitureArrangementMuipData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&HomeFurnitureArrangementMuipData.proto\x1a\x0cVector.proto\"p\n HomeFurnitureArrangementMuipData\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\r\x12\x1a\n\tspawn_pos\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x1a\n\tspawn_rot\x18\x03 \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeFurnitureArrangementMuipData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMEFURNITUREARRANGEMENTMUIPDATA._serialized_start=56
  _HOMEFURNITUREARRANGEMENTMUIPDATA._serialized_end=168
# @@protoc_insertion_point(module_scope)
