# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeLimitedShopBuyGoodsReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeLimitedShopGoods_pb2 as HomeLimitedShopGoods__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n HomeLimitedShopBuyGoodsReq.proto\x1a\x1aHomeLimitedShopGoods.proto\"U\n\x1aHomeLimitedShopBuyGoodsReq\x12$\n\x05goods\x18\x03 \x01(\x0b\x32\x15.HomeLimitedShopGoods\x12\x11\n\tbuy_count\x18\n \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeLimitedShopBuyGoodsReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOMELIMITEDSHOPBUYGOODSREQ._serialized_start=64
  _HOMELIMITEDSHOPBUYGOODSREQ._serialized_end=149
# @@protoc_insertion_point(module_scope)
