# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InBattleMechanicusEscapeMonsterNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+InBattleMechanicusEscapeMonsterNotify.proto\"D\n%InBattleMechanicusEscapeMonsterNotify\x12\x1b\n\x13\x65scaped_monster_num\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InBattleMechanicusEscapeMonsterNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INBATTLEMECHANICUSESCAPEMONSTERNOTIFY._serialized_start=47
  _INBATTLEMECHANICUSESCAPEMONSTERNOTIFY._serialized_end=115
# @@protoc_insertion_point(module_scope)
