# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InBattleMechanicusSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MultistageSettleWatcherInfo_pb2 as MultistageSettleWatcherInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"InBattleMechanicusSettleInfo.proto\x1a!MultistageSettleWatcherInfo.proto\"\xfa\x01\n\x1cInBattleMechanicusSettleInfo\x12\x15\n\rscene_time_ms\x18\x0c \x01(\x04\x12\x12\n\nis_success\x18\r \x01(\x08\x12\x10\n\x08group_id\x18\n \x01(\r\x12\x1b\n\x13Unk3300_EKAIAPLNIPM\x18\t \x01(\r\x12\x1b\n\x13Unk3300_HAEOPAOBBFE\x18\x04 \x01(\r\x12\x1b\n\x13Unk3300_NAMBBHMJJLN\x18\x0b \x01(\r\x12\x12\n\nplay_index\x18\x08 \x01(\r\x12\x32\n\x0cwatcher_list\x18\x0f \x03(\x0b\x32\x1c.MultistageSettleWatcherInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InBattleMechanicusSettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INBATTLEMECHANICUSSETTLEINFO._serialized_start=74
  _INBATTLEMECHANICUSSETTLEINFO._serialized_end=324
# @@protoc_insertion_point(module_scope)
