# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InstableSpraySettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dInstableSpraySettleInfo.proto\"j\n\x17InstableSpraySettleInfo\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x12\x12\n\nscore_list\x18\x04 \x03(\r\x12\x15\n\ris_new_record\x18\r \x01(\x08\x12\x12\n\ndifficulty\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InstableSpraySettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTABLESPRAYSETTLEINFO._serialized_start=33
  _INSTABLESPRAYSETTLEINFO._serialized_end=139
# @@protoc_insertion_point(module_scope)
