# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InvestigationMonsterUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import InvestigationMonster_pb2 as InvestigationMonster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&InvestigationMonsterUpdateNotify.proto\x1a\x1aInvestigationMonster.proto\"X\n InvestigationMonsterUpdateNotify\x12\x34\n\x15investigation_monster\x18\x06 \x01(\x0b\x32\x15.InvestigationMonsterb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InvestigationMonsterUpdateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVESTIGATIONMONSTERUPDATENOTIFY._serialized_start=70
  _INVESTIGATIONMONSTERUPDATENOTIFY._serialized_end=158
# @@protoc_insertion_point(module_scope)
