# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IrodoriChessEntranceDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IrodoriChessEntranceInfo_pb2 as IrodoriChessEntranceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$IrodoriChessEntranceDetailInfo.proto\x1a\x1eIrodoriChessEntranceInfo.proto\"N\n\x1eIrodoriChessEntranceDetailInfo\x12,\n\tinfo_list\x18\x0e \x03(\x0b\x32\x19.IrodoriChessEntranceInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IrodoriChessEntranceDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IRODORICHESSENTRANCEDETAILINFO._serialized_start=72
  _IRODORICHESSENTRANCEDETAILINFO._serialized_end=150
# @@protoc_insertion_point(module_scope)
