# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IrodoriPoetryData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IrodoriPoetryThemeData_pb2 as IrodoriPoetryThemeData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17IrodoriPoetryData.proto\x1a\x1cIrodoriPoetryThemeData.proto\"[\n\x11IrodoriPoetryData\x12\x30\n\x0ftheme_data_list\x18\x02 \x03(\x0b\x32\x17.IrodoriPoetryThemeData\x12\x14\n\x0c\x63ur_theme_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IrodoriPoetryData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IRODORIPOETRYDATA._serialized_start=57
  _IRODORIPOETRYDATA._serialized_end=148
# @@protoc_insertion_point(module_scope)
