# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IslandPartyStageData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aIslandPartyStageData.proto\"M\n\x14IslandPartyStageData\x12\x12\n\nbest_score\x18\x0e \x01(\r\x12\x10\n\x08stage_id\x18\x03 \x01(\r\x12\x0f\n\x07is_open\x18\t \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IslandPartyStageData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ISLANDPARTYSTAGEDATA._serialized_start=30
  _ISLANDPARTYSTAGEDATA._serialized_end=107
# @@protoc_insertion_point(module_scope)
