# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemCdGroupTimeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bItemCdGroupTimeNotify.proto\"\x85\x01\n\x15ItemCdGroupTimeNotify\x12:\n\x0bitem_cd_map\x18\t \x03(\x0b\x32%.ItemCdGroupTimeNotify.ItemCdMapEntry\x1a\x30\n\x0eItemCdMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemCdGroupTimeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMCDGROUPTIMENOTIFY_ITEMCDMAPENTRY._options = None
  _ITEMCDGROUPTIMENOTIFY_ITEMCDMAPENTRY._serialized_options = b'8\001'
  _ITEMCDGROUPTIMENOTIFY._serialized_start=32
  _ITEMCDGROUPTIMENOTIFY._serialized_end=165
  _ITEMCDGROUPTIMENOTIFY_ITEMCDMAPENTRY._serialized_start=117
  _ITEMCDGROUPTIMENOTIFY_ITEMCDMAPENTRY._serialized_end=165
# @@protoc_insertion_point(module_scope)
