# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinHomeWorldFailNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dJoinHomeWorldFailNotify.proto\">\n\x17JoinHomeWorldFailNotify\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x12\x12\n\ntarget_uid\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JoinHomeWorldFailNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINHOMEWORLDFAILNOTIFY._serialized_start=33
  _JOINHOMEWORLDFAILNOTIFY._serialized_end=95
# @@protoc_insertion_point(module_scope)
