# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanternRiteFireworksStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LanternRiteFireworksChallengeInfo_pb2 as LanternRiteFireworksChallengeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#LanternRiteFireworksStageInfo.proto\x1a\'LanternRiteFireworksChallengeInfo.proto\"\x83\x01\n\x1dLanternRiteFireworksStageInfo\x12\x10\n\x08stage_id\x18\x0e \x01(\r\x12\x0f\n\x07is_open\x18\t \x01(\x08\x12?\n\x13\x63hallenge_info_list\x18\x0b \x03(\x0b\x32\".LanternRiteFireworksChallengeInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LanternRiteFireworksStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANTERNRITEFIREWORKSSTAGEINFO._serialized_start=81
  _LANTERNRITEFIREWORKSSTAGEINFO._serialized_end=212
# @@protoc_insertion_point(module_scope)
