# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanternRiteFireworksChallengeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'LanternRiteFireworksChallengeInfo.proto\"d\n!LanternRiteFireworksChallengeInfo\x12\x12\n\nbest_score\x18\x02 \x01(\r\x12\x15\n\ris_full_score\x18\x03 \x01(\x08\x12\x14\n\x0c\x63hallenge_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LanternRiteFireworksChallengeInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANTERNRITEFIREWORKSCHALLENGEINFO._serialized_start=43
  _LANTERNRITEFIREWORKSCHALLENGEINFO._serialized_end=143
# @@protoc_insertion_point(module_scope)
