# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanternRiteDoFireworksReformReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%LanternRiteDoFireworksReformReq.proto\"n\n\x1fLanternRiteDoFireworksReformReq\x12\x10\n\x08stage_id\x18\x0f \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\r \x01(\r\x12\x11\n\tfactor_id\x18\t \x01(\r\x12\x10\n\x08skill_id\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LanternRiteDoFireworksReformReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANTERNRITEDOFIREWORKSREFORMREQ._serialized_start=41
  _LANTERNRITEDOFIREWORKSREFORMREQ._serialized_end=151
# @@protoc_insertion_point(module_scope)
