# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanternRiteDoFireworksReformRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LanternRiteFireworksReformFactorInfo_pb2 as LanternRiteFireworksReformFactorInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%LanternRiteDoFireworksReformRsp.proto\x1a*LanternRiteFireworksReformFactorInfo.proto\"\xa1\x02\n\x1fLanternRiteDoFireworksReformRsp\x12?\n\x10\x66\x61\x63tor_info_list\x18\x06 \x03(\x0b\x32%.LanternRiteFireworksReformFactorInfo\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x12\x1b\n\x13Unk3300_BJHGCFANMBI\x18\x0c \x01(\r\x12\x1b\n\x13Unk3300_OMHPIGGDCBO\x18\n \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\t \x01(\r\x12\x1b\n\x13Unk3300_LKOFBPDKEGG\x18\x08 \x01(\r\x12\x10\n\x08is_lucky\x18\x01 \x01(\x08\x12\x1b\n\x13Unk3300_LKKBPAJOCML\x18\x0e \x01(\r\x12\x10\n\x08stage_id\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LanternRiteDoFireworksReformRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANTERNRITEDOFIREWORKSREFORMRSP._serialized_start=86
  _LANTERNRITEDOFIREWORKSREFORMRSP._serialized_end=375
# @@protoc_insertion_point(module_scope)
