# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LuaEnvironmentEffectNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n LuaEnvironmentEffectNotify.proto\"r\n\x1aLuaEnvironmentEffectNotify\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x16\n\x0eint_param_list\x18\x0c \x03(\x05\x12\x14\n\x0c\x65\x66\x66\x65\x63t_alias\x18\x03 \x01(\t\x12\x18\n\x10\x66loat_param_list\x18\x0e \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LuaEnvironmentEffectNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LUAENVIRONMENTEFFECTNOTIFY._serialized_start=36
  _LUAENVIRONMENTEFFECTNOTIFY._serialized_end=150
# @@protoc_insertion_point(module_scope)
