# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LunaRiteHintPointType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bLunaRiteHintPointType.proto*\x84\x01\n\x15LunaRiteHintPointType\x12\"\n\x1eLUNA_RITE_HINT_POINT_TYPE_NONE\x10\x00\x12\"\n\x1eLUNA_RITE_HINT_POINT_TYPE_RUNE\x10\x01\x12#\n\x1fLUNA_RITE_HINT_POINT_TYPE_CHEST\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LunaRiteHintPointType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LUNARITEHINTPOINTTYPE._serialized_start=32
  _LUNARITEHINTPOINTTYPE._serialized_end=164
# @@protoc_insertion_point(module_scope)
