# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LunaRiteHintPointRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LunaRiteHintPoint_pb2 as LunaRiteHintPoint__pb2
import LunaRiteHintStatusType_pb2 as LunaRiteHintStatusType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aLunaRiteHintPointRsp.proto\x1a\x17LunaRiteHintPoint.proto\x1a\x1cLunaRiteHintStatusType.proto\"\x8e\x01\n\x14LunaRiteHintPointRsp\x12\x0f\n\x07\x61rea_id\x18\t \x01(\r\x12&\n\nhint_point\x18\x0b \x03(\x0b\x32\x12.LunaRiteHintPoint\x12,\n\x0bhint_status\x18\x05 \x01(\x0e\x32\x17.LunaRiteHintStatusType\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LunaRiteHintPointRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LUNARITEHINTPOINTRSP._serialized_start=86
  _LUNARITEHINTPOINTRSP._serialized_end=228
# @@protoc_insertion_point(module_scope)
