# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LunaRiteDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LunaRiteAreaInfo_pb2 as LunaRiteAreaInfo__pb2
import LunaRiteHintPoint_pb2 as LunaRiteHintPoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18LunaRiteDetailInfo.proto\x1a\x16LunaRiteAreaInfo.proto\x1a\x17LunaRiteHintPoint.proto\"g\n\x12LunaRiteDetailInfo\x12&\n\nhint_point\x18\x04 \x03(\x0b\x32\x12.LunaRiteHintPoint\x12)\n\x0e\x61rea_info_list\x18\x07 \x03(\x0b\x32\x11.LunaRiteAreaInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LunaRiteDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LUNARITEDETAILINFO._serialized_start=77
  _LUNARITEDETAILINFO._serialized_end=180
# @@protoc_insertion_point(module_scope)
