# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MassiveEntityState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18MassiveEntityState.proto\"P\n\x12MassiveEntityState\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\r\x12\x0e\n\x06obj_id\x18\x02 \x01(\x03\x12\x15\n\relement_state\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MassiveEntityState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MASSIVEENTITYSTATE._serialized_start=28
  _MASSIVEENTITYSTATE._serialized_end=108
# @@protoc_insertion_point(module_scope)
