# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MechanicusInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Uint32Pair_pb2 as Uint32Pair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MechanicusInfo.proto\x1a\x10Uint32Pair.proto\"\xdf\x01\n\x0eMechanicusInfo\x12)\n\x14gear_level_pair_list\x18\x0e \x03(\x0b\x32\x0b.Uint32Pair\x12\x1d\n\x15open_sequence_id_list\x18\x07 \x03(\r\x12\x0c\n\x04\x63oin\x18\x08 \x01(\r\x12\x18\n\x10punish_over_time\x18\x0c \x01(\r\x12\x15\n\rmechanicus_id\x18\n \x01(\r\x12#\n\x1b\x66inish_difficult_level_list\x18\r \x03(\r\x12\x1f\n\x17is_finish_teach_dungeon\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MechanicusInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MECHANICUSINFO._serialized_start=43
  _MECHANICUSINFO._serialized_end=266
# @@protoc_insertion_point(module_scope)
