# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MichiaeMatsuriRemoveChallengeMarkNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-MichiaeMatsuriRemoveChallengeMarkNotify.proto\"N\n\'MichiaeMatsuriRemoveChallengeMarkNotify\x12\x10\n\x08group_id\x18\n \x01(\r\x12\x11\n\tgadget_id\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MichiaeMatsuriRemoveChallengeMarkNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MICHIAEMATSURIREMOVECHALLENGEMARKNOTIFY._serialized_start=49
  _MICHIAEMATSURIREMOVECHALLENGEMARKNOTIFY._serialized_end=127
# @@protoc_insertion_point(module_scope)
