# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonsterAlertChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eMonsterAlertChangeNotify.proto\"c\n\x18MonsterAlertChangeNotify\x12\x1b\n\x13monster_entity_list\x18\x05 \x03(\r\x12\x10\n\x08is_alert\x18\x0c \x01(\r\x12\x18\n\x10\x61vatar_entity_id\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MonsterAlertChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONSTERALERTCHANGENOTIFY._serialized_start=34
  _MONSTERALERTCHANGENOTIFY._serialized_end=133
# @@protoc_insertion_point(module_scope)
