# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MultistagePlayInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MultistagePlayInfo_pb2 as MultistagePlayInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eMultistagePlayInfoNotify.proto\x1a\x18MultistagePlayInfo.proto\"=\n\x18MultistagePlayInfoNotify\x12!\n\x04info\x18\x05 \x01(\x0b\x32\x13.MultistagePlayInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MultistagePlayInfoNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTISTAGEPLAYINFONOTIFY._serialized_start=60
  _MULTISTAGEPLAYINFONOTIFY._serialized_end=121
# @@protoc_insertion_point(module_scope)
