# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MuqadasPotionDungeonSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&MuqadasPotionDungeonSettleNotify.proto\"\x94\x01\n MuqadasPotionDungeonSettleNotify\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x15\n\ris_new_record\x18\x05 \x01(\x08\x12\x10\n\x08level_id\x18\x08 \x01(\r\x12\x1e\n\x16\x63\x61pture_weakness_count\x18\x03 \x01(\r\x12\x13\n\x0b\x66inal_score\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MuqadasPotionDungeonSettleNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUQADASPOTIONDUNGEONSETTLENOTIFY._serialized_start=43
  _MUQADASPOTIONDUNGEONSETTLENOTIFY._serialized_end=191
# @@protoc_insertion_point(module_scope)
