# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpActivityStateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import OpActivityTagBriefInfo_pb2 as OpActivityTagBriefInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bOpActivityStateNotify.proto\x1a\x1cOpActivityTagBriefInfo.proto\"\x7f\n\x15OpActivityStateNotify\x12\'\n\x1f\x66inished_bonus_activity_id_list\x18\x0e \x03(\r\x12=\n\x1copened_op_activity_info_list\x18\r \x03(\x0b\x32\x17.OpActivityTagBriefInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OpActivityStateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPACTIVITYSTATENOTIFY._serialized_start=61
  _OPACTIVITYSTATENOTIFY._serialized_end=188
# @@protoc_insertion_point(module_scope)
