# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ParentQuest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChildQuest_pb2 as ChildQuest__pb2
import InferencePageInfo_pb2 as InferencePageInfo__pb2
import ParentQuestRandomInfo_pb2 as ParentQuestRandomInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ParentQuest.proto\x1a\x10\x43hildQuest.proto\x1a\x17InferencePageInfo.proto\x1a\x1bParentQuestRandomInfo.proto\"\x9a\x03\n\x0bParentQuest\x12/\n\x13inference_page_list\x18\x05 \x03(\x0b\x32\x12.InferencePageInfo\x12\x11\n\tquest_var\x18\x07 \x03(\x05\x12\x11\n\tvideo_key\x18\x0b \x01(\x04\x12\x1b\n\x13Unk3300_BOMOHKDHMNH\x18\x0f \x01(\r\x12+\n\x0brandom_info\x18\t \x01(\x0b\x32\x16.ParentQuestRandomInfo\x12\x17\n\x0fparent_quest_id\x18\x03 \x01(\r\x12\x11\n\tis_random\x18\x0c \x01(\x08\x12%\n\x10\x63hild_quest_list\x18\x08 \x03(\x0b\x32\x0b.ChildQuest\x12\x13\n\x0bis_finished\x18\x01 \x01(\x08\x12\x32\n\x0ctime_var_map\x18\x02 \x03(\x0b\x32\x1c.ParentQuest.TimeVarMapEntry\x12\x1b\n\x13Unk3300_PCIHJLPPHNJ\x18\x0e \x01(\r\x1a\x31\n\x0fTimeVarMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ParentQuest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARENTQUEST_TIMEVARMAPENTRY._options = None
  _PARENTQUEST_TIMEVARMAPENTRY._serialized_options = b'8\001'
  _PARENTQUEST._serialized_start=94
  _PARENTQUEST._serialized_end=504
  _PARENTQUEST_TIMEVARMAPENTRY._serialized_start=455
  _PARENTQUEST_TIMEVARMAPENTRY._serialized_end=504
# @@protoc_insertion_point(module_scope)
