# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PersistentDungeonSwitchAvatarReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&PersistentDungeonSwitchAvatarReq.proto\"Z\n PersistentDungeonSwitchAvatarReq\x12\x17\n\x0f\x63ur_avatar_guid\x18\x0e \x01(\x04\x12\x1d\n\x15\x61vatar_team_guid_list\x18\x02 \x03(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PersistentDungeonSwitchAvatarReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSISTENTDUNGEONSWITCHAVATARREQ._serialized_start=42
  _PERSISTENTDUNGEONSWITCHAVATARREQ._serialized_end=132
# @@protoc_insertion_point(module_scope)
