# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlantFlowerSetFlowerWishRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!PlantFlowerSetFlowerWishRsp.proto\"C\n\x1bPlantFlowerSetFlowerWishRsp\x12\x13\n\x0bschedule_id\x18\x07 \x01(\r\x12\x0f\n\x07retcode\x18\x08 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlantFlowerSetFlowerWishRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANTFLOWERSETFLOWERWISHRSP._serialized_start=37
  _PLANTFLOWERSETFLOWERWISHRSP._serialized_end=104
# @@protoc_insertion_point(module_scope)
