# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerRechargeDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ProductPriceTier_pb2 as ProductPriceTier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ePlayerRechargeDataNotify.proto\x1a\x16ProductPriceTier.proto\"p\n\x18PlayerRechargeDataNotify\x12\x32\n\x17product_price_tier_list\x18\x07 \x03(\x0b\x32\x11.ProductPriceTier\x12 \n\x18\x63\x61rd_product_remain_days\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerRechargeDataNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERRECHARGEDATANOTIFY._serialized_start=58
  _PLAYERRECHARGEDATANOTIFY._serialized_end=170
# @@protoc_insertion_point(module_scope)
