# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerWorldLocationInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlayerLocationInfo_pb2 as PlayerLocationInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dPlayerWorldLocationInfo.proto\x1a\x18PlayerLocationInfo.proto\"T\n\x17PlayerWorldLocationInfo\x12\'\n\nplayer_loc\x18\x03 \x01(\x0b\x32\x13.PlayerLocationInfo\x12\x10\n\x08scene_id\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerWorldLocationInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERWORLDLOCATIONINFO._serialized_start=59
  _PLAYERWORLDLOCATIONINFO._serialized_end=143
# @@protoc_insertion_point(module_scope)
