# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerMatchStopNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MatchReason_pb2 as MatchReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bPlayerMatchStopNotify.proto\x1a\x11MatchReason.proto\"G\n\x15PlayerMatchStopNotify\x12\x1c\n\x06reason\x18\n \x01(\x0e\x32\x0c.MatchReason\x12\x10\n\x08host_uid\x18\x08 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerMatchStopNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERMATCHSTOPNOTIFY._serialized_start=50
  _PLAYERMATCHSTOPNOTIFY._serialized_end=121
# @@protoc_insertion_point(module_scope)
