# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerReportReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ReportReasonType_pb2 as ReportReasonType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PlayerReportReq.proto\x1a\x16ReportReasonType.proto\"\x99\x01\n\x0fPlayerReportReq\x12!\n\x06reason\x18\x0c \x01(\x0e\x32\x11.ReportReasonType\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\x1d\n\x15target_home_module_id\x18\x05 \x01(\r\x12\x1f\n\x17target_home_module_name\x18\x06 \x01(\t\x12\x12\n\ntarget_uid\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerReportReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERREPORTREQ._serialized_start=50
  _PLAYERREPORTREQ._serialized_end=203
# @@protoc_insertion_point(module_scope)
