# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerApplyEnterMpAfterMatchAgreedNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MatchType_pb2 as MatchType__pb2
import OnlinePlayerInfo_pb2 as OnlinePlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.PlayerApplyEnterMpAfterMatchAgreedNotify.proto\x1a\x0fMatchType.proto\x1a\x16OnlinePlayerInfo.proto\"\x8e\x01\n(PlayerApplyEnterMpAfterMatchAgreedNotify\x12*\n\x0fsrc_player_info\x18\x0b \x01(\x0b\x32\x11.OnlinePlayerInfo\x12\x16\n\x0ematchserver_id\x18\n \x01(\r\x12\x1e\n\nmatch_type\x18\x03 \x01(\x0e\x32\n.MatchTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerApplyEnterMpAfterMatchAgreedNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERAPPLYENTERMPAFTERMATCHAGREEDNOTIFY._serialized_start=92
  _PLAYERAPPLYENTERMPAFTERMATCHAGREEDNOTIFY._serialized_end=234
# @@protoc_insertion_point(module_scope)
