# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerCancelMatchReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MatchType_pb2 as MatchType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPlayerCancelMatchReq.proto\x1a\x0fMatchType.proto\"6\n\x14PlayerCancelMatchReq\x12\x1e\n\nmatch_type\x18\x0b \x01(\x0e\x32\n.MatchTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerCancelMatchReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERCANCELMATCHREQ._serialized_start=47
  _PLAYERCANCELMATCHREQ._serialized_end=101
# @@protoc_insertion_point(module_scope)
