# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerCompoundMaterialRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CompoundQueueData_pb2 as CompoundQueueData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fPlayerCompoundMaterialRsp.proto\x1a\x17\x43ompoundQueueData.proto\"]\n\x19PlayerCompoundMaterialRsp\x12/\n\x13\x63ompound_queue_data\x18\t \x01(\x0b\x32\x12.CompoundQueueData\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerCompoundMaterialRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERCOMPOUNDMATERIALRSP._serialized_start=60
  _PLAYERCOMPOUNDMATERIALRSP._serialized_end=153
# @@protoc_insertion_point(module_scope)
