# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerGCGMatchDismissNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MatchReason_pb2 as MatchReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!PlayerGCGMatchDismissNotify.proto\x1a\x11MatchReason.proto\"_\n\x1bPlayerGCGMatchDismissNotify\x12\x10\n\x08uid_list\x18\x0b \x03(\r\x12\x1c\n\x06reason\x18\x07 \x01(\x0e\x32\x0c.MatchReason\x12\x10\n\x08match_id\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerGCGMatchDismissNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERGCGMATCHDISMISSNOTIFY._serialized_start=56
  _PLAYERGCGMATCHDISMISSNOTIFY._serialized_end=151
# @@protoc_insertion_point(module_scope)
