# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerLuaShellNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_JOEPIGNPDGH_pb2 as Unk2700__JOEPIGNPDGH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPlayerLuaShellNotify.proto\x1a\x19Unk2700_JOEPIGNPDGH.proto\"z\n\x14PlayerLuaShellNotify\x12\x31\n\x13Unk2700_JJMHFFHNJJO\x18\x07 \x01(\x0e\x32\x14.Unk2700_JOEPIGNPDGH\x12\n\n\x02id\x18\x05 \x01(\r\x12\x11\n\tlua_shell\x18\x0c \x01(\x0c\x12\x10\n\x08use_type\x18\n \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerLuaShellNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERLUASHELLNOTIFY._serialized_start=57
  _PLAYERLUASHELLNOTIFY._serialized_end=179
# @@protoc_insertion_point(module_scope)
