# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PotionStage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_JLHKOLGFAMI_pb2 as Unk2700__JLHKOLGFAMI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PotionStage.proto\x1a\x19Unk2700_JLHKOLGFAMI.proto\"\x94\x01\n\x0bPotionStage\x12\x10\n\x08stage_id\x18\x0b \x01(\r\x12\x1b\n\x13Unk2700_HFHCCJFDOKA\x18\x02 \x03(\r\x12\x0f\n\x07is_open\x18\x0f \x01(\x08\x12(\n\nlevel_list\x18\x0e \x03(\x0b\x32\x14.Unk2700_JLHKOLGFAMI\x12\x1b\n\x13Unk2700_LONIJGBDPIG\x18\r \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PotionStage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POTIONSTAGE._serialized_start=49
  _POTIONSTAGE._serialized_end=197
# @@protoc_insertion_point(module_scope)
