# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProudSkillExtraLevelNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ProudSkillExtraLevelNotify.proto\"q\n\x1aProudSkillExtraLevelNotify\x12\x13\n\x0btalent_type\x18\x0b \x01(\r\x12\x14\n\x0ctalent_index\x18\x08 \x01(\r\x12\x13\n\x0b\x61vatar_guid\x18\x0f \x01(\x04\x12\x13\n\x0b\x65xtra_level\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProudSkillExtraLevelNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROUDSKILLEXTRALEVELNOTIFY._serialized_start=36
  _PROUDSKILLEXTRALEVELNOTIFY._serialized_end=149
# @@protoc_insertion_point(module_scope)
