# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullRecentChatRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatInfo_pb2 as ChatInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PullRecentChatRsp.proto\x1a\x0e\x43hatInfo.proto\"B\n\x11PullRecentChatRsp\x12\x1c\n\tchat_info\x18\r \x03(\x0b\x32\t.ChatInfo\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PullRecentChatRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PULLRECENTCHATRSP._serialized_start=43
  _PULLRECENTCHATRSP._serialized_end=109
# @@protoc_insertion_point(module_scope)
