# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuestGlobalVarNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import QuestGlobalVar_pb2 as QuestGlobalVar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aQuestGlobalVarNotify.proto\x1a\x14QuestGlobalVar.proto\"9\n\x14QuestGlobalVarNotify\x12!\n\x08var_list\x18\x08 \x03(\x0b\x32\x0f.QuestGlobalVarb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuestGlobalVarNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUESTGLOBALVARNOTIFY._serialized_start=52
  _QUESTGLOBALVARNOTIFY._serialized_end=109
# @@protoc_insertion_point(module_scope)
