# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReliquaryDecomposeRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bReliquaryDecomposeRsp.proto\";\n\x15ReliquaryDecomposeRsp\x12\x11\n\tguid_list\x18\x06 \x03(\x04\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReliquaryDecomposeRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RELIQUARYDECOMPOSERSP._serialized_start=31
  _RELIQUARYDECOMPOSERSP._serialized_end=90
# @@protoc_insertion_point(module_scope)
