# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReliquaryUpgradeRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ReliquaryUpgradeRsp.proto\"\xbc\x01\n\x13ReliquaryUpgradeRsp\x12\x1b\n\x13Unk3300_MGELABLMFOE\x18\r \x03(\r\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12\x1d\n\x15target_reliquary_guid\x18\x0e \x01(\x04\x12\x11\n\tcur_level\x18\x02 \x01(\r\x12\x11\n\told_level\x18\x06 \x01(\r\x12\x1b\n\x13Unk3300_IALPGNADFKA\x18\n \x03(\r\x12\x15\n\rpower_up_rate\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReliquaryUpgradeRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RELIQUARYUPGRADERSP._serialized_start=30
  _RELIQUARYUPGRADERSP._serialized_end=218
# @@protoc_insertion_point(module_scope)
