# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResinCardData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ResinCardData.proto\"s\n\rResinCardData\x12\x1a\n\x12remain_reward_days\x18\x03 \x01(\r\x12\x13\n\x0b\x65xpire_time\x18\x0c \x01(\r\x12\x1e\n\x16last_daily_reward_time\x18\x02 \x01(\r\x12\x11\n\tconfig_id\x18\x07 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResinCardData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESINCARDDATA._serialized_start=23
  _RESINCARDDATA._serialized_end=138
# @@protoc_insertion_point(module_scope)
