# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueDungeonPlayerCellChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(RogueDungeonPlayerCellChangeNotify.proto\"J\n\"RogueDungeonPlayerCellChangeNotify\x12\x0f\n\x07\x63\x65ll_id\x18\x04 \x01(\r\x12\x13\n\x0bold_cell_id\x18\x07 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueDungeonPlayerCellChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROGUEDUNGEONPLAYERCELLCHANGENOTIFY._serialized_start=44
  _ROGUEDUNGEONPLAYERCELLCHANGENOTIFY._serialized_end=118
# @@protoc_insertion_point(module_scope)
