# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueCellState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RogueCellState.proto*\xa5\x01\n\x0eRogueCellState\x12\x19\n\x15ROGUE_CELL_STATE_NONE\x10\x00\x12\x1b\n\x17ROGUE_CELL_STATE_BATTLE\x10\x01\x12\x1c\n\x18ROGUE_CELL_STATE_SUCCESS\x10\x02\x12\x1b\n\x17ROGUE_CELL_STATE_FINISH\x10\x03\x12 \n\x1cROGUE_CELL_STATE_TAKEN_CHEST\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueCellState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROGUECELLSTATE._serialized_start=25
  _ROGUECELLSTATE._serialized_end=190
# @@protoc_insertion_point(module_scope)
