# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SaveCustomDungeonRoomRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CustomDungeonBlock_pb2 as CustomDungeonBlock__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSaveCustomDungeonRoomRsp.proto\x1a\x18\x43ustomDungeonBlock.proto\"k\n\x18SaveCustomDungeonRoomRsp\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12\x0f\n\x07room_id\x18\x03 \x01(\r\x12-\n\x10\x65rror_block_list\x18\x08 \x03(\x0b\x32\x13.CustomDungeonBlockb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SaveCustomDungeonRoomRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAVECUSTOMDUNGEONROOMRSP._serialized_start=60
  _SAVECUSTOMDUNGEONROOMRSP._serialized_end=167
# @@protoc_insertion_point(module_scope)
