# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SaveUgcReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UgcMusicBriefInfo_pb2 as UgcMusicBriefInfo__pb2
import UgcMusicRecord_pb2 as UgcMusicRecord__pb2
import UgcType_pb2 as UgcType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SaveUgcReq.proto\x1a\x17UgcMusicBriefInfo.proto\x1a\x14UgcMusicRecord.proto\x1a\rUgcType.proto\"\x95\x01\n\nSaveUgcReq\x12\x1a\n\x08ugc_type\x18\x03 \x01(\x0e\x32\x08.UgcType\x12\'\n\x0cmusic_record\x18\x0b \x01(\x0b\x32\x0f.UgcMusicRecordH\x00\x12/\n\x10music_brief_info\x18\x84\x02 \x01(\x0b\x32\x12.UgcMusicBriefInfoH\x01\x42\x08\n\x06recordB\x07\n\x05\x62riefb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SaveUgcReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAVEUGCREQ._serialized_start=83
  _SAVEUGCREQ._serialized_end=232
# @@protoc_insertion_point(module_scope)
