# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SaveUgcRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UgcType_pb2 as UgcType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SaveUgcRsp.proto\x1a\rUgcType.proto\"K\n\nSaveUgcRsp\x12\x10\n\x08ugc_guid\x18\t \x01(\x04\x12\x0f\n\x07retcode\x18\x08 \x01(\x05\x12\x1a\n\x08ugc_type\x18\x02 \x01(\x0e\x32\x08.UgcTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SaveUgcRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAVEUGCRSP._serialized_start=35
  _SAVEUGCRSP._serialized_end=110
# @@protoc_insertion_point(module_scope)
