# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGalleryVintageHuntingFirstStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.SceneGalleryVintageHuntingFirstStageInfo.proto\"\x90\x01\n(SceneGalleryVintageHuntingFirstStageInfo\x12\x1b\n\x13Unk3100_BKOPHMFCPGD\x18\x0f \x01(\r\x12\x1b\n\x13Unk3100_OMMEHLGCBHP\x18\x07 \x01(\r\x12\r\n\x05score\x18\x0e \x01(\r\x12\x1b\n\x13Unk3100_KCFEMMIGNPG\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGalleryVintageHuntingFirstStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEGALLERYVINTAGEHUNTINGFIRSTSTAGEINFO._serialized_start=51
  _SCENEGALLERYVINTAGEHUNTINGFIRSTSTAGEINFO._serialized_end=195
# @@protoc_insertion_point(module_scope)
