# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenePlayBattleUidOpNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ScenePlayBattleUidOpNotify.proto\"\xe0\x01\n\x1aScenePlayBattleUidOpNotify\x12\n\n\x02op\x18\x05 \x01(\r\x12\x16\n\x0eparam_duration\x18\n \x01(\r\x12\x0f\n\x07play_id\x18\r \x01(\r\x12\x19\n\x11param_target_list\x18\x0c \x03(\r\x12\x11\n\tentity_id\x18\x02 \x01(\r\x12\x12\n\nparam_list\x18\t \x03(\r\x12\x11\n\tparam_str\x18\x0b \x01(\t\x12\x13\n\x0bparam_index\x18\x0f \x01(\r\x12\x10\n\x08uid_list\x18\x06 \x03(\r\x12\x11\n\tplay_type\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScenePlayBattleUidOpNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEPLAYBATTLEUIDOPNOTIFY._serialized_start=37
  _SCENEPLAYBATTLEUIDOPNOTIFY._serialized_end=261
# @@protoc_insertion_point(module_scope)
