# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneTeamUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneTeamAvatar_pb2 as SceneTeamAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSceneTeamUpdateNotify.proto\x1a\x15SceneTeamAvatar.proto\"[\n\x15SceneTeamUpdateNotify\x12\x30\n\x16scene_team_avatar_list\x18\x0b \x03(\x0b\x32\x10.SceneTeamAvatar\x12\x10\n\x08is_in_mp\x18\x07 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneTeamUpdateNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENETEAMUPDATENOTIFY._serialized_start=54
  _SCENETEAMUPDATENOTIFY._serialized_end=145
# @@protoc_insertion_point(module_scope)
