# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityDisappearNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VisionType_pb2 as VisionType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SceneEntityDisappearNotify.proto\x1a\x10VisionType.proto\"e\n\x1aSceneEntityDisappearNotify\x12\r\n\x05param\x18\x06 \x01(\r\x12\x13\n\x0b\x65ntity_list\x18\x01 \x03(\r\x12#\n\x0e\x64isappear_type\x18\x02 \x01(\x0e\x32\x0b.VisionTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityDisappearNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEENTITYDISAPPEARNOTIFY._serialized_start=54
  _SCENEENTITYDISAPPEARNOTIFY._serialized_end=155
# @@protoc_insertion_point(module_scope)
