# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneAreaWeatherNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSceneAreaWeatherNotify.proto\"\xfb\x01\n\x16SceneAreaWeatherNotify\x12\x19\n\x11weather_gadget_id\x18\x06 \x01(\r\x12G\n\x11weather_value_map\x18\x0b \x03(\x0b\x32,.SceneAreaWeatherNotify.WeatherValueMapEntry\x12\x14\n\x0c\x63limate_type\x18\x07 \x01(\r\x12\x16\n\x0etrans_duration\x18\n \x01(\x02\x12\x17\n\x0fweather_area_id\x18\x0f \x01(\r\x1a\x36\n\x14WeatherValueMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneAreaWeatherNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEAREAWEATHERNOTIFY_WEATHERVALUEMAPENTRY._options = None
  _SCENEAREAWEATHERNOTIFY_WEATHERVALUEMAPENTRY._serialized_options = b'8\001'
  _SCENEAREAWEATHERNOTIFY._serialized_start=33
  _SCENEAREAWEATHERNOTIFY._serialized_end=284
  _SCENEAREAWEATHERNOTIFY_WEATHERVALUEMAPENTRY._serialized_start=230
  _SCENEAREAWEATHERNOTIFY_WEATHERVALUEMAPENTRY._serialized_end=284
# @@protoc_insertion_point(module_scope)
