# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneWeatherForcastRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSceneWeatherForcastRsp.proto\"b\n\x16SceneWeatherForcastRsp\x12\x19\n\x11next_climate_time\x18\x0e \x01(\x04\x12\x1c\n\x14\x66orcast_climate_list\x18\x02 \x03(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneWeatherForcastRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEWEATHERFORCASTRSP._serialized_start=32
  _SCENEWEATHERFORCASTRSP._serialized_end=130
# @@protoc_insertion_point(module_scope)
