# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGalleryBalloonInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BalloonPlayerInfo_pb2 as BalloonPlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSceneGalleryBalloonInfo.proto\x1a\x17\x42\x61lloonPlayerInfo.proto\"\xe1\x01\n\x17SceneGalleryBalloonInfo\x12^\n\x1dscene_player_balloon_info_map\x18\r \x03(\x0b\x32\x37.SceneGalleryBalloonInfo.ScenePlayerBalloonInfoMapEntry\x12\x10\n\x08\x65nd_time\x18\t \x01(\r\x1aT\n\x1eScenePlayerBalloonInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.BalloonPlayerInfo:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGalleryBalloonInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEGALLERYBALLOONINFO_SCENEPLAYERBALLOONINFOMAPENTRY._options = None
  _SCENEGALLERYBALLOONINFO_SCENEPLAYERBALLOONINFOMAPENTRY._serialized_options = b'8\001'
  _SCENEGALLERYBALLOONINFO._serialized_start=59
  _SCENEGALLERYBALLOONINFO._serialized_end=284
  _SCENEGALLERYBALLOONINFO_SCENEPLAYERBALLOONINFOMAPENTRY._serialized_start=200
  _SCENEGALLERYBALLOONINFO_SCENEPLAYERBALLOONINFOMAPENTRY._serialized_end=284
# @@protoc_insertion_point(module_scope)
