# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneSurfaceMaterial.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSceneSurfaceMaterial.proto*\xa3\x02\n\x14SceneSurfaceMaterial\x12\"\n\x1eSCENE_SURFACE_MATERIAL_INVALID\x10\x00\x12 \n\x1cSCENE_SURFACE_MATERIAL_GRASS\x10\x01\x12\x1f\n\x1bSCENE_SURFACE_MATERIAL_DIRT\x10\x02\x12\x1f\n\x1bSCENE_SURFACE_MATERIAL_ROCK\x10\x03\x12\x1f\n\x1bSCENE_SURFACE_MATERIAL_SNOW\x10\x04\x12 \n\x1cSCENE_SURFACE_MATERIAL_WATER\x10\x05\x12\x1f\n\x1bSCENE_SURFACE_MATERIAL_TILE\x10\x06\x12\x1f\n\x1bSCENE_SURFACE_MATERIAL_SAND\x10\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneSurfaceMaterial_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENESURFACEMATERIAL._serialized_start=31
  _SCENESURFACEMATERIAL._serialized_end=322
# @@protoc_insertion_point(module_scope)
