# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGalleryHandballInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlaceInfo_pb2 as PlaceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSceneGalleryHandballInfo.proto\x1a\x0fPlaceInfo.proto\"U\n\x18SceneGalleryHandballInfo\x12#\n\x0f\x62\x61ll_place_info\x18\t \x01(\x0b\x32\n.PlaceInfo\x12\x14\n\x0cis_have_ball\x18\x0f \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGalleryHandballInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEGALLERYHANDBALLINFO._serialized_start=51
  _SCENEGALLERYHANDBALLINFO._serialized_end=136
# @@protoc_insertion_point(module_scope)
