# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneCreateEntityRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CreateEntityInfo_pb2 as CreateEntityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSceneCreateEntityRsp.proto\x1a\x16\x43reateEntityInfo.proto\"]\n\x14SceneCreateEntityRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x12\x11\n\tentity_id\x18\x01 \x01(\r\x12!\n\x06\x65ntity\x18\n \x01(\x0b\x32\x11.CreateEntityInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneCreateEntityRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENECREATEENTITYRSP._serialized_start=54
  _SCENECREATEENTITYRSP._serialized_end=147
# @@protoc_insertion_point(module_scope)
