# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SeaLampActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSeaLampActivityDetailInfo.proto\"\xbc\x01\n\x19SeaLampActivityDetailInfo\x12\x10\n\x08phase_id\x18\x0e \x01(\r\x12\x1f\n\x17taken_phase_reward_list\x18\x01 \x03(\r\x12&\n\x1etaken_contribution_reward_list\x18\x07 \x03(\r\x12\x10\n\x08progress\x18\x08 \x01(\r\x12\x14\n\x0c\x63ontribution\x18\x0f \x01(\r\x12\x0e\n\x06\x66\x61\x63tor\x18\r \x01(\r\x12\x0c\n\x04\x64\x61ys\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SeaLampActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEALAMPACTIVITYDETAILINFO._serialized_start=36
  _SEALAMPACTIVITYDETAILINFO._serialized_end=224
# @@protoc_insertion_point(module_scope)
