# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SeaLampContributeItemRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSeaLampContributeItemRsp.proto\"{\n\x18SeaLampContributeItemRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x12\x1b\n\x13Unk3300_AIINHBHNHOI\x18\x0b \x01(\r\x12\x14\n\x0c\x61\x64\x64_progress\x18\x05 \x01(\r\x12\x1b\n\x13Unk3300_LPHALOGLGAL\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SeaLampContributeItemRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEALAMPCONTRIBUTEITEMRSP._serialized_start=34
  _SEALAMPCONTRIBUTEITEMRSP._serialized_end=157
# @@protoc_insertion_point(module_scope)
