# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SealBattleEndNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SealBattleEndNotify.proto\"=\n\x13SealBattleEndNotify\x12\x16\n\x0eseal_entity_id\x18\x0b \x01(\r\x12\x0e\n\x06is_win\x18\x0c \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SealBattleEndNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEALBATTLEENDNOTIFY._serialized_start=29
  _SEALBATTLEENDNOTIFY._serialized_end=90
# @@protoc_insertion_point(module_scope)
