# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetUpLunchBoxWidgetRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LunchBoxData_pb2 as LunchBoxData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSetUpLunchBoxWidgetRsp.proto\x1a\x12LunchBoxData.proto\"P\n\x16SetUpLunchBoxWidgetRsp\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x12%\n\x0elunch_box_data\x18\x02 \x01(\x0b\x32\r.LunchBoxDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetUpLunchBoxWidgetRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUPLUNCHBOXWIDGETRSP._serialized_start=52
  _SETUPLUNCHBOXWIDGETRSP._serialized_end=132
# @@protoc_insertion_point(module_scope)
