# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShopMcoinProduct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ShopMcoinProduct.proto\"\xa2\x01\n\x10ShopMcoinProduct\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x12\n\nprice_tier\x18\x02 \x01(\t\x12\x12\n\nmcoin_base\x18\x03 \x01(\r\x12\x17\n\x0fmcoin_non_first\x18\x04 \x01(\r\x12\x13\n\x0bmcoin_first\x18\x05 \x01(\r\x12\x12\n\nbought_num\x18\x06 \x01(\r\x12\x10\n\x08is_audit\x18\x07 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ShopMcoinProduct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHOPMCOINPRODUCT._serialized_start=27
  _SHOPMCOINPRODUCT._serialized_end=189
# @@protoc_insertion_point(module_scope)
