# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StoreItemChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Item_pb2 as Item__pb2
import StoreType_pb2 as StoreType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bStoreItemChangeNotify.proto\x1a\nItem.proto\x1a\x0fStoreType.proto\"Q\n\x15StoreItemChangeNotify\x12\x1e\n\nstore_type\x18\x04 \x01(\x0e\x32\n.StoreType\x12\x18\n\titem_list\x18\x05 \x03(\x0b\x32\x05.Itemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StoreItemChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOREITEMCHANGENOTIFY._serialized_start=60
  _STOREITEMCHANGENOTIFY._serialized_end=141
# @@protoc_insertion_point(module_scope)
