# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummerTimeSprintBoatRecord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SummerTimeSprintBoatRecord.proto\"\x83\x01\n\x1aSummerTimeSprintBoatRecord\x12\x12\n\nbest_score\x18\x03 \x01(\r\x12\x12\n\nstart_time\x18\r \x01(\r\x12\x12\n\nis_touched\x18\x07 \x01(\x08\x12\x17\n\x0fwatcher_id_list\x18\n \x03(\r\x12\x10\n\x08group_id\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SummerTimeSprintBoatRecord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMERTIMESPRINTBOATRECORD._serialized_start=37
  _SUMMERTIMESPRINTBOATRECORD._serialized_end=168
# @@protoc_insertion_point(module_scope)
