# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummerTimeV2BoatGallerySettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStopReason_pb2 as GalleryStopReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'SummerTimeV2BoatGallerySettleInfo.proto\x1a\x17GalleryStopReason.proto\"\x9e\x01\n!SummerTimeV2BoatGallerySettleInfo\x12\"\n\x06reason\x18\n \x01(\x0e\x32\x12.GalleryStopReason\x12\x0e\n\x06param2\x18\x0c \x01(\r\x12\x11\n\tused_time\x18\x04 \x01(\r\x12\x0e\n\x06param1\x18\x07 \x01(\r\x12\x12\n\ngallery_id\x18\x0b \x01(\r\x12\x0e\n\x06param3\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SummerTimeV2BoatGallerySettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMERTIMEV2BOATGALLERYSETTLEINFO._serialized_start=69
  _SUMMERTIMEV2BOATGALLERYSETTLEINFO._serialized_end=227
# @@protoc_insertion_point(module_scope)
