# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummerTimeSprintBoatSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&SummerTimeSprintBoatSettleNotify.proto\"\xce\x01\n SummerTimeSprintBoatSettleNotify\x12\r\n\x05score\x18\x06 \x01(\r\x12\x11\n\tleft_time\x18\x02 \x01(\r\x12\x12\n\nis_success\x18\x04 \x01(\x08\x12\x10\n\x08group_id\x18\x05 \x01(\r\x12\x1b\n\x13Unk3300_PLFMJPNPPLI\x18\x0c \x01(\r\x12\x11\n\ttotal_num\x18\n \x01(\r\x12\x15\n\ris_new_record\x18\x0f \x01(\x08\x12\x1b\n\x13Unk3300_MEEKFJJIOKE\x18\x0e \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SummerTimeSprintBoatSettleNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMERTIMESPRINTBOATSETTLENOTIFY._serialized_start=43
  _SUMMERTIMESPRINTBOATSETTLENOTIFY._serialized_end=249
# @@protoc_insertion_point(module_scope)
