# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummerTimeDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SummerTimeSprintBoatInfo_pb2 as SummerTimeSprintBoatInfo__pb2
import SummerTimeStageInfo_pb2 as SummerTimeStageInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSummerTimeDetailInfo.proto\x1a\x1eSummerTimeSprintBoatInfo.proto\x1a\x19SummerTimeStageInfo.proto\"\x81\x02\n\x14SummerTimeDetailInfo\x12\x36\n\tstage_map\x18\t \x03(\x0b\x32#.SummerTimeDetailInfo.StageMapEntry\x12\x33\n\x10sprint_boat_info\x18\x01 \x01(\x0b\x32\x19.SummerTimeSprintBoatInfo\x12\x19\n\x11is_content_closed\x18\r \x01(\x08\x12\x1a\n\x12\x63ontent_close_time\x18\x0c \x01(\r\x1a\x45\n\rStageMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.SummerTimeStageInfo:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SummerTimeDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMERTIMEDETAILINFO_STAGEMAPENTRY._options = None
  _SUMMERTIMEDETAILINFO_STAGEMAPENTRY._serialized_options = b'8\001'
  _SUMMERTIMEDETAILINFO._serialized_start=90
  _SUMMERTIMEDETAILINFO._serialized_end=347
  _SUMMERTIMEDETAILINFO_STAGEMAPENTRY._serialized_start=278
  _SUMMERTIMEDETAILINFO_STAGEMAPENTRY._serialized_end=347
# @@protoc_insertion_point(module_scope)
