# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SumoSelectTeamAndEnterDungeonRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SumoTeamData_pb2 as SumoTeamData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&SumoSelectTeamAndEnterDungeonRsp.proto\x1a\x12SumoTeamData.proto\"\x93\x01\n SumoSelectTeamAndEnterDungeonRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x13\n\x0b\x61\x63tivity_id\x18\x0e \x01(\r\x12\x15\n\rdifficulty_id\x18\x0c \x01(\r\x12\x10\n\x08stage_id\x18\t \x01(\r\x12 \n\tteam_list\x18\x02 \x03(\x0b\x32\r.SumoTeamDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SumoSelectTeamAndEnterDungeonRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMOSELECTTEAMANDENTERDUNGEONRSP._serialized_start=63
  _SUMOSELECTTEAMANDENTERDUNGEONRSP._serialized_end=210
# @@protoc_insertion_point(module_scope)
