# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SumoSetNoSwitchPunishTimeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SumoDungeonTeam_pb2 as SumoDungeonTeam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SumoSetNoSwitchPunishTimeNotify.proto\x1a\x15SumoDungeonTeam.proto\"\xcc\x01\n\x1fSumoSetNoSwitchPunishTimeNotify\x12\x10\n\x08stage_id\x18\x0f \x01(\r\x12\x1b\n\x13Unk3300_CBAMLHDMKJF\x18\n \x01(\r\x12\x13\n\x0b\x61\x63tivity_id\x18\x05 \x01(\r\x12\x1b\n\x13Unk3300_BNJBIGHIJOC\x18\x03 \x01(\r\x12\x1b\n\x13Unk3300_DJBJACGHGDM\x18\t \x01(\r\x12+\n\x11\x64ungeon_team_list\x18\x02 \x03(\x0b\x32\x10.SumoDungeonTeamb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SumoSetNoSwitchPunishTimeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMOSETNOSWITCHPUNISHTIMENOTIFY._serialized_start=65
  _SUMOSETNOSWITCHPUNISHTIMENOTIFY._serialized_end=269
# @@protoc_insertion_point(module_scope)
