# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SumoSwitchTeamRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SumoDungeonTeam_pb2 as SumoDungeonTeam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SumoSwitchTeamRsp.proto\x1a\x15SumoDungeonTeam.proto\"\xb0\x01\n\x11SumoSwitchTeamRsp\x12\x1e\n\x16next_valid_switch_time\x18\x07 \x01(\r\x12+\n\x11\x64ungeon_team_list\x18\n \x03(\x0b\x32\x10.SumoDungeonTeam\x12\x13\n\x0b\x61\x63tivity_id\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x12\x16\n\x0e\x63ur_team_index\x18\x0b \x01(\r\x12\x10\n\x08stage_id\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SumoSwitchTeamRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMOSWITCHTEAMRSP._serialized_start=51
  _SUMOSWITCHTEAMRSP._serialized_end=227
# @@protoc_insertion_point(module_scope)
