# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeMaterialDeleteReturnReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MaterialDeleteReturnType_pb2 as MaterialDeleteReturnType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!TakeMaterialDeleteReturnReq.proto\x1a\x1eMaterialDeleteReturnType.proto\"F\n\x1bTakeMaterialDeleteReturnReq\x12\'\n\x04type\x18\x08 \x01(\x0e\x32\x19.MaterialDeleteReturnTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeMaterialDeleteReturnReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAKEMATERIALDELETERETURNREQ._serialized_start=69
  _TAKEMATERIALDELETERETURNREQ._serialized_end=139
# @@protoc_insertion_point(module_scope)
