# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeReunionMissionRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ReunionMissionInfo_pb2 as ReunionMissionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!TakeReunionMissionRewardRsp.proto\x1a\x18ReunionMissionInfo.proto\"\x82\x01\n\x1bTakeReunionMissionRewardRsp\x12\x14\n\x0creward_index\x18\x0c \x01(\r\x12\x0f\n\x07retcode\x18\x02 \x01(\x05\x12)\n\x0cmission_info\x18\t \x01(\x0b\x32\x13.ReunionMissionInfo\x12\x11\n\treward_id\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeReunionMissionRewardRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAKEREUNIONMISSIONREWARDRSP._serialized_start=64
  _TAKEREUNIONMISSIONREWARDRSP._serialized_end=194
# @@protoc_insertion_point(module_scope)
