# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TanukiTravelActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_BIFNFOGBPNM_pb2 as Unk2700__BIFNFOGBPNM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$TanukiTravelActivityDetailInfo.proto\x1a\x19Unk2700_BIFNFOGBPNM.proto\"\x8b\x01\n\x1eTanukiTravelActivityDetailInfo\x12\x31\n\x13Unk2700_JBPFIDDPGME\x18\x04 \x03(\x0b\x32\x14.Unk2700_BIFNFOGBPNM\x12\x19\n\x11is_content_closed\x18\x0b \x01(\x08\x12\x1b\n\x13Unk2700_BHHCNOLMCJM\x18\n \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TanukiTravelActivityDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TANUKITRAVELACTIVITYDETAILINFO._serialized_start=68
  _TANUKITRAVELACTIVITYDETAILINFO._serialized_end=207
# @@protoc_insertion_point(module_scope)
