# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TowerAllDataRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TowerCurLevelRecord_pb2 as TowerCurLevelRecord__pb2
import TowerFloorRecord_pb2 as TowerFloorRecord__pb2
import TowerMonthlyBrief_pb2 as TowerMonthlyBrief__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15TowerAllDataRsp.proto\x1a\x19TowerCurLevelRecord.proto\x1a\x16TowerFloorRecord.proto\x1a\x17TowerMonthlyBrief.proto\"\x95\x06\n\x0fTowerAllDataRsp\x12\x1b\n\x13Unk3300_HCDFJBHMHHF\x18\x06 \x01(\r\x12\x1b\n\x13Unk3300_ILDODKDADMI\x18\x08 \x01(\r\x12\x19\n\x11is_first_interact\x18\x05 \x01(\x08\x12\x19\n\x11tower_schedule_id\x18\x01 \x01(\r\x12\x1b\n\x13Unk3300_JBACKENDHDG\x18\n \x01(\r\x12\x1c\n\x13Unk3300_KGHOIIAEIHH\x18\xe2\x04 \x01(\r\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12\x1b\n\x13Unk3300_OHCHCJGJIDK\x18\x04 \x01(\r\x12\x1b\n\x13Unk3300_BBHKBDDFPFE\x18\x02 \x01(\r\x12\x38\n\x1blast_schedule_monthly_brief\x18\xdd\t \x01(\x0b\x32\x12.TowerMonthlyBrief\x12.\n\x10\x63ur_level_record\x18\x0c \x01(\x0b\x32\x14.TowerCurLevelRecord\x12\x32\n\x17tower_floor_record_list\x18\r \x03(\x0b\x32\x11.TowerFloorRecord\x12)\n\rmonthly_brief\x18\t \x01(\x0b\x32\x12.TowerMonthlyBrief\x12\x1b\n\x13Unk3300_LEKODCFPINJ\x18\x07 \x01(\r\x12\x45\n\x13Unk3300_PJPEEJACFJH\x18\x03 \x03(\x0b\x32(.TowerAllDataRsp.Unk3300PJPEEJACFJHEntry\x12\"\n\x1ais_finished_entrance_floor\x18\x0f \x01(\x08\x12\x45\n\x13Unk3300_GNINCLBMMDJ\x18\x0e \x03(\x0b\x32(.TowerAllDataRsp.Unk3300GNINCLBMMDJEntry\x1a\x39\n\x17Unk3300PJPEEJACFJHEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x39\n\x17Unk3300GNINCLBMMDJEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TowerAllDataRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOWERALLDATARSP_UNK3300PJPEEJACFJHENTRY._options = None
  _TOWERALLDATARSP_UNK3300PJPEEJACFJHENTRY._serialized_options = b'8\001'
  _TOWERALLDATARSP_UNK3300GNINCLBMMDJENTRY._options = None
  _TOWERALLDATARSP_UNK3300GNINCLBMMDJENTRY._serialized_options = b'8\001'
  _TOWERALLDATARSP._serialized_start=102
  _TOWERALLDATARSP._serialized_end=891
  _TOWERALLDATARSP_UNK3300PJPEEJACFJHENTRY._serialized_start=775
  _TOWERALLDATARSP_UNK3300PJPEEJACFJHENTRY._serialized_end=832
  _TOWERALLDATARSP_UNK3300GNINCLBMMDJENTRY._serialized_start=834
  _TOWERALLDATARSP_UNK3300GNINCLBMMDJENTRY._serialized_end=891
# @@protoc_insertion_point(module_scope)
