# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TowerLevelStarCondData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cTowerLevelStarCondData.proto\"t\n\x16TowerLevelStarCondData\x12\x1b\n\x13Unk2700_HIFMJMAHEMB\x18\x0f \x01(\x08\x12\x12\n\ncond_value\x18\t \x01(\r\x12\x10\n\x08is_pause\x18\r \x01(\x08\x12\x17\n\x0fstar_cond_index\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TowerLevelStarCondData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOWERLEVELSTARCONDDATA._serialized_start=32
  _TOWERLEVELSTARCONDDATA._serialized_end=148
# @@protoc_insertion_point(module_scope)
