# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TowerLevelStarCondNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TowerLevelStarCondData_pb2 as TowerLevelStarCondData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eTowerLevelStarCondNotify.proto\x1a\x1cTowerLevelStarCondData.proto\"r\n\x18TowerLevelStarCondNotify\x12\x13\n\x0blevel_index\x18\x0e \x01(\r\x12\x10\n\x08\x66loor_id\x18\x0b \x01(\r\x12/\n\x0e\x63ond_data_list\x18\t \x03(\x0b\x32\x17.TowerLevelStarCondDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TowerLevelStarCondNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOWERLEVELSTARCONDNOTIFY._serialized_start=64
  _TOWERLEVELSTARCONDNOTIFY._serialized_end=178
# @@protoc_insertion_point(module_scope)
