# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TreasureMapDetectorDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TreasureMapDetectorData_pb2 as TreasureMapDetectorData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#TreasureMapDetectorDataNotify.proto\x1a\x1dTreasureMapDetectorData.proto\"G\n\x1dTreasureMapDetectorDataNotify\x12&\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x18.TreasureMapDetectorDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TreasureMapDetectorDataNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TREASUREMAPDETECTORDATANOTIFY._serialized_start=70
  _TREASUREMAPDETECTORDATANOTIFY._serialized_end=141
# @@protoc_insertion_point(module_scope)
