# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrialAvatarGrantRecord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cTrialAvatarGrantRecord.proto\"\xe6\x04\n\x16TrialAvatarGrantRecord\x12\x14\n\x0cgrant_reason\x18\x01 \x01(\r\x12\x1c\n\x14\x66rom_parent_quest_id\x18\x02 \x01(\r\"\x97\x04\n\x0bGrantReason\x12\x18\n\x14GRANT_REASON_INVALID\x10\x00\x12\x19\n\x15GRANT_REASON_BY_QUEST\x10\x01\x12)\n%GRANT_REASON_BY_TRIAL_AVATAR_ACTIVITY\x10\x02\x12-\n)GRANT_REASON_BY_DUNGEON_ELEMENT_CHALLENGE\x10\x03\x12\'\n#GRANT_REASON_BY_MIST_TRIAL_ACTIVITY\x10\x04\x12!\n\x1dGRANT_REASON_BY_SUMO_ACTIVITY\x10\x05\x12#\n\x1fGRANT_REASON_BY_POTION_ACTIVITY\x10\x06\x12)\n%GRANT_REASON_BY_CRYSTAL_LINK_ACTIVITY\x10\x07\x12\"\n\x1eGRANT_REASON_BY_IRODORI_MASTER\x10\x08\x12\x16\n\x12GRANT_REASON_BY_GM\x10\t\x12+\n\'GRANT_REASON_BY_INSTABLE_SPRAY_ACTIVITY\x10\n\x12+\n\'GRANT_REASON_BY_MUQADAS_POTION_ACTIVITY\x10\x0b\x12#\n\x1fGRANT_REASON_BY_VINTAGE_HUNTING\x10\x0c\x12\"\n\x1eGRANT_REASON_BY_CHAR_AMUSEMENT\x10\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrialAvatarGrantRecord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIALAVATARGRANTRECORD._serialized_start=33
  _TRIALAVATARGRANTRECORD._serialized_end=647
  _TRIALAVATARGRANTRECORD_GRANTREASON._serialized_start=112
  _TRIALAVATARGRANTRECORD_GRANTREASON._serialized_end=647
# @@protoc_insertion_point(module_scope)
