# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TryEnterHomeRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15TryEnterHomeRsp.proto\"J\n\x0fTryEnterHomeRsp\x12\x12\n\ntarget_uid\x18\x0f \x01(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x12\x12\n\nparam_list\x18\n \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TryEnterHomeRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRYENTERHOMERSP._serialized_start=25
  _TRYENTERHOMERSP._serialized_end=99
# @@protoc_insertion_point(module_scope)
