# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_HDBFJJOBIAP_ClientReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_OPEBMJPOOBL_pb2 as Unk2700__OPEBMJPOOBL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_HDBFJJOBIAP_ClientReq.proto\x1a\x19Unk2700_OPEBMJPOOBL.proto\"o\n\x1dUnk2700_HDBFJJOBIAP_ClientReq\x12\x1b\n\x13Unk2700_CEPGMKAHHCD\x18\x07 \x01(\x04\x12\x31\n\x13Unk2700_KHBDAPGDOJA\x18\n \x01(\x0e\x32\x14.Unk2700_OPEBMJPOOBLb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_HDBFJJOBIAP_ClientReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_HDBFJJOBIAP_CLIENTREQ._serialized_start=66
  _UNK2700_HDBFJJOBIAP_CLIENTREQ._serialized_end=177
# @@protoc_insertion_point(module_scope)
