# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_DGDJKHJNLGO.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_PGFLJBBEBKG_pb2 as Unk2700__PGFLJBBEBKG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_DGDJKHJNLGO.proto\x1a\x19Unk2700_PGFLJBBEBKG.proto\"\x8f\x01\n\x13Unk2700_DGDJKHJNLGO\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x1b\n\x13Unk2700_OEFLHAPAMFH\x18\x02 \x03(\x04\x12\x1b\n\x13Unk2700_OJNBAOCJBCH\x18\x03 \x03(\x04\x12\x31\n\x13Unk2700_GDDGEKHOLGL\x18\x04 \x03(\x0b\x32\x14.Unk2700_PGFLJBBEBKGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_DGDJKHJNLGO_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_DGDJKHJNLGO._serialized_start=57
  _UNK2700_DGDJKHJNLGO._serialized_end=200
# @@protoc_insertion_point(module_scope)
