# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2800_BEMANDBNPJB.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExhibitionDisplayInfo_pb2 as ExhibitionDisplayInfo__pb2
import OnlinePlayerInfo_pb2 as OnlinePlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2800_BEMANDBNPJB.proto\x1a\x1b\x45xhibitionDisplayInfo.proto\x1a\x16OnlinePlayerInfo.proto\"h\n\x13Unk2800_BEMANDBNPJB\x12&\n\x0bplayer_info\x18\r \x01(\x0b\x32\x11.OnlinePlayerInfo\x12)\n\tcard_list\x18\x0b \x03(\x0b\x32\x16.ExhibitionDisplayInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2800_BEMANDBNPJB_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2800_BEMANDBNPJB._serialized_start=82
  _UNK2800_BEMANDBNPJB._serialized_end=186
# @@protoc_insertion_point(module_scope)
