# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_HIHKGMLLOGD.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_HIHKGMLLOGD.proto\"\xce\x01\n\x13Unk2700_HIHKGMLLOGD\x12\x1b\n\x13Unk2700_ONOGHAHICAA\x18\x01 \x03(\r\x12\x1b\n\x13Unk2700_FGBAGFMGKOO\x18\x04 \x03(\r\x12\x14\n\x0cmax_progress\x18\x02 \x01(\r\x12\x1b\n\x13Unk2700_OBDGPNILPND\x18\r \x01(\r\x12\x10\n\x08progress\x18\x05 \x01(\r\x12\x1b\n\x13Unk2700_HJNLDGMIHBL\x18\x0c \x01(\r\x12\x1b\n\x13Unk2700_BIMPFNHLMBI\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_HIHKGMLLOGD_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_HIHKGMLLOGD._serialized_start=30
  _UNK2700_HIHKGMLLOGD._serialized_end=236
# @@protoc_insertion_point(module_scope)
