# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_HFMDKDHCJCM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_HFMDKDHCJCM.proto\x1a\x0cVector.proto\";\n\x13Unk2700_HFMDKDHCJCM\x12$\n\x13Unk2700_CMOMNFNGCGB\x18\x01 \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_HFMDKDHCJCM_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_HFMDKDHCJCM._serialized_start=43
  _UNK2700_HFMDKDHCJCM._serialized_end=102
# @@protoc_insertion_point(module_scope)
