# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_IGPIIHEDJLJ_ServerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_KBBDJNLFAKD_pb2 as Unk2700__KBBDJNLFAKD__pb2
import Unk2700_NLFDMMFNMIO_pb2 as Unk2700__NLFDMMFNMIO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_IGPIIHEDJLJ_ServerRsp.proto\x1a\x19Unk2700_KBBDJNLFAKD.proto\x1a\x19Unk2700_NLFDMMFNMIO.proto\"\xa6\x02\n\x1dUnk2700_IGPIIHEDJLJ_ServerRsp\x12\x31\n\x13Unk2700_EJHNBDLLLFO\x18\x0e \x01(\x0b\x32\x14.Unk2700_NLFDMMFNMIO\x12\x31\n\x13Unk2700_LGBODABIKLL\x18\x02 \x01(\x0e\x32\x14.Unk2700_KBBDJNLFAKD\x12\x0f\n\x07retcode\x18\n \x01(\x05\x12S\n\x13Unk2700_DDGNPJLHKKH\x18\x06 \x03(\x0b\x32\x36.Unk2700_IGPIIHEDJLJ_ServerRsp.Unk2700DDGNPJLHKKHEntry\x1a\x39\n\x17Unk2700DDGNPJLHKKHEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_IGPIIHEDJLJ_ServerRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_IGPIIHEDJLJ_SERVERRSP_UNK2700DDGNPJLHKKHENTRY._options = None
  _UNK2700_IGPIIHEDJLJ_SERVERRSP_UNK2700DDGNPJLHKKHENTRY._serialized_options = b'8\001'
  _UNK2700_IGPIIHEDJLJ_SERVERRSP._serialized_start=94
  _UNK2700_IGPIIHEDJLJ_SERVERRSP._serialized_end=388
  _UNK2700_IGPIIHEDJLJ_SERVERRSP_UNK2700DDGNPJLHKKHENTRY._serialized_start=331
  _UNK2700_IGPIIHEDJLJ_SERVERRSP_UNK2700DDGNPJLHKKHENTRY._serialized_end=388
# @@protoc_insertion_point(module_scope)
