# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_EELPPGCAKHL.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_EELPPGCAKHL.proto\"\xb5\x02\n\x13Unk2700_EELPPGCAKHL\x12I\n\x13Unk2700_BMLBMGGBFJG\x18\x0f \x03(\x0b\x32,.Unk2700_EELPPGCAKHL.Unk2700BMLBMGGBFJGEntry\x12I\n\x13Unk2700_OBFPKFEGGIK\x18\x0e \x03(\x0b\x32,.Unk2700_EELPPGCAKHL.Unk2700OBFPKFEGGIKEntry\x12\x12\n\ndungeon_id\x18\x05 \x01(\r\x1a\x39\n\x17Unk2700BMLBMGGBFJGEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x39\n\x17Unk2700OBFPKFEGGIKEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_EELPPGCAKHL_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_EELPPGCAKHL_UNK2700BMLBMGGBFJGENTRY._options = None
  _UNK2700_EELPPGCAKHL_UNK2700BMLBMGGBFJGENTRY._serialized_options = b'8\001'
  _UNK2700_EELPPGCAKHL_UNK2700OBFPKFEGGIKENTRY._options = None
  _UNK2700_EELPPGCAKHL_UNK2700OBFPKFEGGIKENTRY._serialized_options = b'8\001'
  _UNK2700_EELPPGCAKHL._serialized_start=30
  _UNK2700_EELPPGCAKHL._serialized_end=339
  _UNK2700_EELPPGCAKHL_UNK2700BMLBMGGBFJGENTRY._serialized_start=223
  _UNK2700_EELPPGCAKHL_UNK2700BMLBMGGBFJGENTRY._serialized_end=280
  _UNK2700_EELPPGCAKHL_UNK2700OBFPKFEGGIKENTRY._serialized_start=282
  _UNK2700_EELPPGCAKHL_UNK2700OBFPKFEGGIKENTRY._serialized_end=339
# @@protoc_insertion_point(module_scope)
