# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_CCEOEOHLAPK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_CCEOEOHLAPK.proto\x1a\x0cVector.proto\"s\n\x13Unk2700_CCEOEOHLAPK\x12\x15\n\ris_hint_valid\x18\x03 \x01(\x08\x12 \n\x0fhint_center_pos\x18\x08 \x01(\x0b\x32\x07.Vector\x12\x10\n\x08group_id\x18\x06 \x01(\r\x12\x11\n\tconfig_id\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_CCEOEOHLAPK_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_CCEOEOHLAPK._serialized_start=43
  _UNK2700_CCEOEOHLAPK._serialized_end=158
# @@protoc_insertion_point(module_scope)
