# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_JEFIMHGLOJF.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_JEFIMHGLOJF.proto\"u\n\x13Unk2700_JEFIMHGLOJF\x12\x1b\n\x13Unk2700_MCGIJIGJCIG\x18\x04 \x01(\r\x12\x12\n\nis_success\x18\t \x01(\x08\x12\x1b\n\x13Unk2700_LOMDDJKOMCK\x18\x0c \x03(\r\x12\x10\n\x08stage_id\x18\x0f \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_JEFIMHGLOJF_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_JEFIMHGLOJF._serialized_start=29
  _UNK2700_JEFIMHGLOJF._serialized_end=146
# @@protoc_insertion_point(module_scope)
