# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2800_KOMBBIEEGCP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2800_KOMBBIEEGCP.proto\"T\n\x13Unk2800_KOMBBIEEGCP\x12\x12\n\ngallery_id\x18\x02 \x01(\r\x12\x0c\n\x04\x63oin\x18\t \x01(\r\x12\x1b\n\x13Unk2800_LBPCDCHOOLJ\x18\x0b \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2800_KOMBBIEEGCP_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2800_KOMBBIEEGCP._serialized_start=29
  _UNK2800_KOMBBIEEGCP._serialized_end=113
# @@protoc_insertion_point(module_scope)
