# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_IPGJEAEFJMM_ServerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DropSubfieldType_pb2 as DropSubfieldType__pb2
import MusicBriefInfo_pb2 as MusicBriefInfo__pb2
import MusicRecord_pb2 as MusicRecord__pb2
import Unk2700_OPEBMJPOOBL_pb2 as Unk2700__OPEBMJPOOBL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_IPGJEAEFJMM_ServerRsp.proto\x1a\x16\x44ropSubfieldType.proto\x1a\x14MusicBriefInfo.proto\x1a\x11MusicRecord.proto\x1a\x19Unk2700_OPEBMJPOOBL.proto\"\xb2\x02\n\x1dUnk2700_IPGJEAEFJMM_ServerRsp\x12\x1b\n\x13Unk2700_CEPGMKAHHCD\x18\x0f \x01(\x04\x12\x31\n\x13Unk2700_KHBDAPGDOJA\x18\n \x01(\x0e\x32\x14.Unk2700_OPEBMJPOOBL\x12\x0f\n\x07retcode\x18\x02 \x01(\x05\x12.\n\x13Unk2700_MJNIHFCKJMN\x18\x0e \x01(\x0e\x32\x11.DropSubfieldType\x12$\n\x0cmusic_record\x18\x04 \x01(\x0b\x32\x0c.MusicRecordH\x00\x12,\n\x10music_brief_info\x18\x9b\x0e \x01(\x0b\x32\x0f.MusicBriefInfoH\x01\x42\x15\n\x13Unk2700_MIPPJKBFLOOB\x15\n\x13Unk2700_ILHNBMNOMHOb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_IPGJEAEFJMM_ServerRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_IPGJEAEFJMM_SERVERRSP._serialized_start=132
  _UNK2700_IPGJEAEFJMM_SERVERRSP._serialized_end=438
# @@protoc_insertion_point(module_scope)
