# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_FIODAJPNBIK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_AFOPONDCLKC_pb2 as Unk2700__AFOPONDCLKC__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_FIODAJPNBIK.proto\x1a\x19Unk2700_AFOPONDCLKC.proto\"Y\n\x13Unk2700_FIODAJPNBIK\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x12\x31\n\x13Unk2700_MAKCLMEGEBJ\x18\x05 \x03(\x0b\x32\x14.Unk2700_AFOPONDCLKCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_FIODAJPNBIK_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_FIODAJPNBIK._serialized_start=56
  _UNK2700_FIODAJPNBIK._serialized_end=145
# @@protoc_insertion_point(module_scope)
