# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_GCPNGHFNGDP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_GCPNGHFNGDP.proto\x1a\x0fItemParam.proto\"[\n\x13Unk2700_GCPNGHFNGDP\x12\x1b\n\x13Unk2700_ANAEHLBDFIC\x18\x01 \x03(\r\x12\'\n\x13Unk2700_PMMJDKJHBIG\x18\x07 \x03(\x0b\x32\n.ItemParamb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_GCPNGHFNGDP_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_GCPNGHFNGDP._serialized_start=46
  _UNK2700_GCPNGHFNGDP._serialized_end=137
# @@protoc_insertion_point(module_scope)
