# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_EGKIHLIOLDM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_NPOBPFNDJKK_pb2 as Unk2700__NPOBPFNDJKK__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_EGKIHLIOLDM.proto\x1a\x19Unk2700_NPOBPFNDJKK.proto\"X\n\x13Unk2700_EGKIHLIOLDM\x12\x1b\n\x13Unk2700_CDDONJJMFCI\x18\x0e \x01(\r\x12$\n\x06reason\x18\x07 \x01(\x0e\x32\x14.Unk2700_NPOBPFNDJKKb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_EGKIHLIOLDM_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_EGKIHLIOLDM._serialized_start=56
  _UNK2700_EGKIHLIOLDM._serialized_end=144
# @@protoc_insertion_point(module_scope)
