# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_NCNPNMFFONG.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_NCNPNMFFONG.proto*\xd0\x02\n\x13Unk2700_NCNPNMFFONG\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_EOOLPOEEAPH\x10\x00\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_GLPMMPCFDLN\x10\x01\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_MFPLNPDOELM\x10\x02\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_EPFDAAKBKML\x10\x03\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_PMAPHIADDJF\x10\x04\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_BLJLDKHIPGD\x10\x05\x12+\n\'Unk2700_NCNPNMFFONG_Unk2700_EOPEJCDHJCF\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_NCNPNMFFONG_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_NCNPNMFFONG._serialized_start=30
  _UNK2700_NCNPNMFFONG._serialized_end=366
# @@protoc_insertion_point(module_scope)
