# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_MKAFBOPFDEF_ServerNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&Unk2700_MKAFBOPFDEF_ServerNotify.proto\"?\n Unk2700_MKAFBOPFDEF_ServerNotify\x12\x1b\n\x13Unk2700_DFMMBCLLBEN\x18\x05 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_MKAFBOPFDEF_ServerNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_MKAFBOPFDEF_SERVERNOTIFY._serialized_start=42
  _UNK2700_MKAFBOPFDEF_SERVERNOTIFY._serialized_end=105
# @@protoc_insertion_point(module_scope)
