# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_ODJKHILOILK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PotionStage_pb2 as PotionStage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_ODJKHILOILK.proto\x1a\x11PotionStage.proto\"Q\n\x13Unk2700_ODJKHILOILK\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12)\n\x13Unk2700_BBEEMJECIAA\x18\x0e \x01(\x0b\x32\x0c.PotionStageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_ODJKHILOILK_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_ODJKHILOILK._serialized_start=48
  _UNK2700_ODJKHILOILK._serialized_end=129
# @@protoc_insertion_point(module_scope)
