# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_MBIDJDLLBNM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_MBIDJDLLBNM.proto\x1a\x0cVector.proto\"]\n\x13Unk2700_MBIDJDLLBNM\x12\x11\n\topen_time\x18\x05 \x01(\r\x12\n\n\x02id\x18\x01 \x01(\r\x12\x14\n\x03pos\x18\x0e \x01(\x0b\x32\x07.Vector\x12\x11\n\tmax_score\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_MBIDJDLLBNM_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_MBIDJDLLBNM._serialized_start=43
  _UNK2700_MBIDJDLLBNM._serialized_end=136
# @@protoc_insertion_point(module_scope)
