# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_OHBMICGFIIK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_OHBMICGFIIK.proto\"\x89\x01\n\x13Unk2700_OHBMICGFIIK\x12\x1b\n\x13Unk2700_DABMGCIOKCK\x18\x04 \x01(\r\x12\x1b\n\x13Unk2700_BKJABFANBIM\x18\x0c \x01(\r\x12\x1b\n\x13Unk2700_PGBNOPOIHIK\x18\x07 \x01(\r\x12\x1b\n\x13Unk2700_DJNLHEBADGE\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_OHBMICGFIIK_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_OHBMICGFIIK._serialized_start=30
  _UNK2700_OHBMICGFIIK._serialized_end=167
# @@protoc_insertion_point(module_scope)
