# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2800_BPOJIIDEADD.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2800_BPOJIIDEADD.proto\"\x9a\x01\n\x13Unk2800_BPOJIIDEADD\x12\x1b\n\x13Unk2800_MMPELBBNFOD\x18\x08 \x01(\r\x12\x11\n\topen_time\x18\x0b \x01(\r\x12\x1b\n\x13Unk2800_MGPEODNKEEC\x18\x05 \x01(\r\x12\x10\n\x08level_id\x18\x0c \x01(\r\x12\x13\n\x0bis_finished\x18\t \x01(\x08\x12\x0f\n\x07is_open\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2800_BPOJIIDEADD_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2800_BPOJIIDEADD._serialized_start=30
  _UNK2800_BPOJIIDEADD._serialized_end=184
# @@protoc_insertion_point(module_scope)
