# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_MNIBEMEMGMO.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_HJLFNKLPFBH_pb2 as Unk2700__HJLFNKLPFBH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_MNIBEMEMGMO.proto\x1a\x19Unk2700_HJLFNKLPFBH.proto\"\x9f\x01\n\x13Unk2700_MNIBEMEMGMO\x12\x31\n\x13Unk2700_BNHNCPPADPJ\x18\n \x03(\x0b\x32\x14.Unk2700_HJLFNKLPFBH\x12\x1b\n\x13Unk2700_KGMFDCOMCOF\x18\x06 \x01(\r\x12\x1b\n\x13Unk2700_MLMJABGLDPH\x18\x08 \x01(\r\x12\x1b\n\x13Unk2700_NHMJKBGEHID\x18\x07 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_MNIBEMEMGMO_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_MNIBEMEMGMO._serialized_start=57
  _UNK2700_MNIBEMEMGMO._serialized_end=216
# @@protoc_insertion_point(module_scope)
