# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_BEDCCMDPNCH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_BKHBKHINBIA_pb2 as Unk2700__BKHBKHINBIA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_BEDCCMDPNCH.proto\x1a\x19Unk2700_BKHBKHINBIA.proto\"T\n\x13Unk2700_BEDCCMDPNCH\x12\x12\n\ngallery_id\x18\x0e \x01(\r\x12)\n\x0bsettle_info\x18\x0f \x01(\x0b\x32\x14.Unk2700_BKHBKHINBIAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_BEDCCMDPNCH_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_BEDCCMDPNCH._serialized_start=56
  _UNK2700_BEDCCMDPNCH._serialized_end=140
# @@protoc_insertion_point(module_scope)
