# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_GBPNAHCAKJE.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_EDNGHJGKEKC_pb2 as Unk2700__EDNGHJGKEKC__pb2
import Unk2700_LBPFDCBHCBL_pb2 as Unk2700__LBPFDCBHCBL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_GBPNAHCAKJE.proto\x1a\x19Unk2700_EDNGHJGKEKC.proto\x1a\x19Unk2700_LBPFDCBHCBL.proto\"\xf3\x01\n\x13Unk2700_GBPNAHCAKJE\x12\x1b\n\x13Unk2700_OAKBDKKBFHP\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12\x1b\n\x13Unk2700_NDEJPMGPBAH\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\r\x12\x31\n\x13Unk2700_LHPECOEIIKL\x18\x07 \x03(\x0b\x32\x14.Unk2700_EDNGHJGKEKC\x12\x31\n\x13Unk2700_LABLGMEOEFM\x18\x08 \x03(\x0b\x32\x14.Unk2700_LBPFDCBHCBLb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_GBPNAHCAKJE_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_GBPNAHCAKJE._serialized_start=84
  _UNK2700_GBPNAHCAKJE._serialized_end=327
# @@protoc_insertion_point(module_scope)
