# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_GNDOKLHDHBJ_ClientReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_GNDOKLHDHBJ_ClientReq.proto\"0\n\x1dUnk2700_GNDOKLHDHBJ_ClientReq\x12\x0f\n\x07room_id\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_GNDOKLHDHBJ_ClientReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_GNDOKLHDHBJ_CLIENTREQ._serialized_start=39
  _UNK2700_GNDOKLHDHBJ_CLIENTREQ._serialized_end=87
# @@protoc_insertion_point(module_scope)
