# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_NFGNGFLNOOJ_ServerNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_CHLNIDHHGLE_pb2 as Unk2700__CHLNIDHHGLE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&Unk2700_NFGNGFLNOOJ_ServerNotify.proto\x1a\x19Unk2700_CHLNIDHHGLE.proto\"\x95\x01\n Unk2700_NFGNGFLNOOJ_ServerNotify\x12\x12\n\ngallery_id\x18\x01 \x01(\r\x12)\n\x0bsettle_info\x18\x05 \x01(\x0b\x32\x14.Unk2700_CHLNIDHHGLE\x12\x1b\n\x13Unk2700_HAOPLFPOLFM\x18\x06 \x01(\r\x12\x15\n\ris_new_record\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_NFGNGFLNOOJ_ServerNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_NFGNGFLNOOJ_SERVERNOTIFY._serialized_start=70
  _UNK2700_NFGNGFLNOOJ_SERVERNOTIFY._serialized_end=219
# @@protoc_insertion_point(module_scope)
