# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_CLMGFEOPNFH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_CLMGFEOPNFH.proto\":\n\x13Unk2700_CLMGFEOPNFH\x12\x0f\n\x07retcode\x18\n \x01(\x05\x12\x12\n\ngallery_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_CLMGFEOPNFH_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_CLMGFEOPNFH._serialized_start=29
  _UNK2700_CLMGFEOPNFH._serialized_end=87
# @@protoc_insertion_point(module_scope)
