# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_JCNIPOJMFMH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_EEPNCOAEKBM_pb2 as Unk2700__EEPNCOAEKBM__pb2
import Unk2700_LELADCCDNJH_pb2 as Unk2700__LELADCCDNJH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_JCNIPOJMFMH.proto\x1a\x19Unk2700_EEPNCOAEKBM.proto\x1a\x19Unk2700_LELADCCDNJH.proto\"\xc2\x01\n\x13Unk2700_JCNIPOJMFMH\x12\x31\n\x13Unk2700_OCBDODAGPNF\x18\x0c \x03(\x0e\x32\x14.Unk2700_EEPNCOAEKBM\x12(\n\nlevel_list\x18\x06 \x03(\x0b\x32\x14.Unk2700_LELADCCDNJH\x12\x1b\n\x13Unk2700_EGPCJLGGGLK\x18\n \x03(\r\x12\x31\n\x13Unk2700_CPJMLMCOCLA\x18\r \x03(\x0e\x32\x14.Unk2700_EEPNCOAEKBMb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_JCNIPOJMFMH_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_JCNIPOJMFMH._serialized_start=84
  _UNK2700_JCNIPOJMFMH._serialized_end=278
# @@protoc_insertion_point(module_scope)
