# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_IEGOOOECBFH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_HIHKGMLLOGD_pb2 as Unk2700__HIHKGMLLOGD__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk2700_IEGOOOECBFH.proto\x1a\x19Unk2700_HIHKGMLLOGD.proto\"Y\n\x13Unk2700_IEGOOOECBFH\x12\x31\n\x13Unk2700_BABEGIGEEIB\x18\r \x01(\x0b\x32\x14.Unk2700_HIHKGMLLOGD\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_IEGOOOECBFH_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_IEGOOOECBFH._serialized_start=56
  _UNK2700_IEGOOOECBFH._serialized_end=145
# @@protoc_insertion_point(module_scope)
