# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_FNHKFHGNLPP_ServerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk2700_GHHCCEHGKLH_pb2 as Unk2700__GHHCCEHGKLH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_FNHKFHGNLPP_ServerRsp.proto\x1a\x19Unk2700_GHHCCEHGKLH.proto\"c\n\x1dUnk2700_FNHKFHGNLPP_ServerRsp\x12\x31\n\x13Unk2700_BCIBEPMFLGN\x18\x08 \x03(\x0b\x32\x14.Unk2700_GHHCCEHGKLH\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_FNHKFHGNLPP_ServerRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_FNHKFHGNLPP_SERVERRSP._serialized_start=66
  _UNK2700_FNHKFHGNLPP_SERVERRSP._serialized_end=165
# @@protoc_insertion_point(module_scope)
