# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk2700_JOHOODKBINN_ClientReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Unk2700_JOHOODKBINN_ClientReq.proto\x1a\x0cVector.proto\"]\n\x1dUnk2700_JOHOODKBINN_ClientReq\x12\x14\n\x03pos\x18\n \x01(\x0b\x32\x07.Vector\x12\x11\n\tentity_id\x18\x0f \x01(\r\x12\x13\n\x0bmaterial_id\x18\x06 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk2700_JOHOODKBINN_ClientReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK2700_JOHOODKBINN_CLIENTREQ._serialized_start=53
  _UNK2700_JOHOODKBINN_CLIENTREQ._serialized_end=146
# @@protoc_insertion_point(module_scope)
