# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3000_CMEPCFFDIGL.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk3000_GDKMIBFADKD_pb2 as Unk3000__GDKMIBFADKD__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3000_CMEPCFFDIGL.proto\x1a\x19Unk3000_GDKMIBFADKD.proto\"W\n\x13Unk3000_CMEPCFFDIGL\x12\r\n\x05level\x18\n \x01(\x05\x12\x31\n\x13Unk3000_MKIJEIKFIJP\x18\x06 \x03(\x0b\x32\x14.Unk3000_GDKMIBFADKDb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3000_CMEPCFFDIGL_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3000_CMEPCFFDIGL._serialized_start=56
  _UNK3000_CMEPCFFDIGL._serialized_end=143
# @@protoc_insertion_point(module_scope)
