# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3100_MCIBDBBEKEK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3100_MCIBDBBEKEK.proto\"O\n\x13Unk3100_MCIBDBBEKEK\x12\x1b\n\x13Unk3100_NNOCAMHJFAO\x18\x08 \x03(\r\x12\x1b\n\x13Unk3100_NDGIJLCIEDB\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3100_MCIBDBBEKEK_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3100_MCIBDBBEKEK._serialized_start=29
  _UNK3100_MCIBDBBEKEK._serialized_end=108
# @@protoc_insertion_point(module_scope)
