# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3000_PKHPBOIDLEA.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3000_PKHPBOIDLEA.proto*\xc9\x01\n\x13Unk3000_PKHPBOIDLEA\x12+\n\'Unk3000_PKHPBOIDLEA_Unk3000_KANMGBLJEHC\x10\x00\x12+\n\'Unk3000_PKHPBOIDLEA_Unk3000_ICFILKDKFNL\x10\x01\x12+\n\'Unk3000_PKHPBOIDLEA_Unk3000_FBFKPBGLMAD\x10\x02\x12+\n\'Unk3000_PKHPBOIDLEA_Unk3000_KEOIEIKLFDN\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3000_PKHPBOIDLEA_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3000_PKHPBOIDLEA._serialized_start=30
  _UNK3000_PKHPBOIDLEA._serialized_end=231
# @@protoc_insertion_point(module_scope)
