# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3000_NNPCGEAHNHM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk3000_BOBIJEDOFKG_pb2 as Unk3000__BOBIJEDOFKG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3000_NNPCGEAHNHM.proto\x1a\x19Unk3000_BOBIJEDOFKG.proto\"H\n\x13Unk3000_NNPCGEAHNHM\x12\x31\n\x13Unk3000_ALGOLKMONEF\x18\x08 \x03(\x0b\x32\x14.Unk3000_BOBIJEDOFKGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3000_NNPCGEAHNHM_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3000_NNPCGEAHNHM._serialized_start=56
  _UNK3000_NNPCGEAHNHM._serialized_end=128
# @@protoc_insertion_point(module_scope)
