# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3000_GDMEIKLAMIB.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3000_GDMEIKLAMIB.proto\"L\n\x13Unk3000_GDMEIKLAMIB\x12\x10\n\x08group_id\x18\x06 \x01(\r\x12\x10\n\x08scene_id\x18\t \x01(\r\x12\x11\n\tconfig_id\x18\x0c \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3000_GDMEIKLAMIB_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3000_GDMEIKLAMIB._serialized_start=29
  _UNK3000_GDMEIKLAMIB._serialized_end=105
# @@protoc_insertion_point(module_scope)
