# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3000_GDKMIBFADKD.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Unk3000_GDKMIBFADKD.proto\x1a\x0cVector.proto\"X\n\x13Unk3000_GDKMIBFADKD\x12\r\n\x05index\x18\x08 \x01(\x03\x12\x0c\n\x04\x61rea\x18\x05 \x01(\x05\x12$\n\x13Unk3000_AOEGLPPFIFD\x18\x01 \x01(\x0b\x32\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3000_GDKMIBFADKD_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3000_GDKMIBFADKD._serialized_start=43
  _UNK3000_GDKMIBFADKD._serialized_end=131
# @@protoc_insertion_point(module_scope)
