# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unk3100_JKGDHFGAJMH_ThirdStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(Unk3100_JKGDHFGAJMH_ThirdStageInfo.proto\"K\n\"Unk3100_JKGDHFGAJMH_ThirdStageInfo\x12\x11\n\tleft_time\x18\r \x01(\r\x12\x12\n\nis_success\x18\t \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unk3100_JKGDHFGAJMH_ThirdStageInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNK3100_JKGDHFGAJMH_THIRDSTAGEINFO._serialized_start=44
  _UNK3100_JKGDHFGAJMH_THIRDSTAGEINFO._serialized_end=119
# @@protoc_insertion_point(module_scope)
