# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnlockedFurnitureSuiteDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&UnlockedFurnitureSuiteDataNotify.proto\"S\n UnlockedFurnitureSuiteDataNotify\x12\x0e\n\x06is_all\x18\x01 \x01(\x08\x12\x1f\n\x17\x66urniture_suite_id_list\x18\x03 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UnlockedFurnitureSuiteDataNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNLOCKEDFURNITURESUITEDATANOTIFY._serialized_start=42
  _UNLOCKEDFURNITURESUITEDATANOTIFY._serialized_end=125
# @@protoc_insertion_point(module_scope)
