# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VintagePresentStageData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VintagePresentLevelData_pb2 as VintagePresentLevelData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dVintagePresentStageData.proto\x1a\x1dVintagePresentLevelData.proto\"\xfe\x01\n\x17VintagePresentStageData\x12\x0f\n\x07is_open\x18\x04 \x01(\x08\x12\x11\n\tis_finish\x18\n \x01(\x08\x12H\n\x11present_level_map\x18\x0b \x03(\x0b\x32-.VintagePresentStageData.PresentLevelMapEntry\x12\x11\n\topen_time\x18\x08 \x01(\r\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x1aP\n\x14PresentLevelMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.VintagePresentLevelData:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VintagePresentStageData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VINTAGEPRESENTSTAGEDATA_PRESENTLEVELMAPENTRY._options = None
  _VINTAGEPRESENTSTAGEDATA_PRESENTLEVELMAPENTRY._serialized_options = b'8\001'
  _VINTAGEPRESENTSTAGEDATA._serialized_start=65
  _VINTAGEPRESENTSTAGEDATA._serialized_end=319
  _VINTAGEPRESENTSTAGEDATA_PRESENTLEVELMAPENTRY._serialized_start=239
  _VINTAGEPRESENTSTAGEDATA_PRESENTLEVELMAPENTRY._serialized_end=319
# @@protoc_insertion_point(module_scope)
