# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetGadgetAllDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetGadgetData_pb2 as WidgetGadgetData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fWidgetGadgetAllDataNotify.proto\x1a\x16WidgetGadgetData.proto\"J\n\x19WidgetGadgetAllDataNotify\x12-\n\x12widget_gadget_data\x18\x01 \x03(\x0b\x32\x11.WidgetGadgetDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetGadgetAllDataNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIDGETGADGETALLDATANOTIFY._serialized_start=59
  _WIDGETGADGETALLDATANOTIFY._serialized_end=133
# @@protoc_insertion_point(module_scope)
