# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetCreatorInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetCreateLocationInfo_pb2 as WidgetCreateLocationInfo__pb2
import WidgetCreatorOpType_pb2 as WidgetCreatorOpType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17WidgetCreatorInfo.proto\x1a\x1eWidgetCreateLocationInfo.proto\x1a\x19WidgetCreatorOpType.proto\"\x7f\n\x11WidgetCreatorInfo\x12%\n\x07op_type\x18\x0e \x01(\x0e\x32\x14.WidgetCreatorOpType\x12\x11\n\tentity_id\x18\x0c \x01(\r\x12\x30\n\rlocation_info\x18\t \x01(\x0b\x32\x19.WidgetCreateLocationInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetCreatorInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIDGETCREATORINFO._serialized_start=86
  _WIDGETCREATORINFO._serialized_end=213
# @@protoc_insertion_point(module_scope)
