# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WindFieldDungeonSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Unk3100_HJALLGOLFGL_pb2 as Unk3100__HJALLGOLFGL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n WindFieldDungeonSettleInfo.proto\x1a\x19Unk3100_HJALLGOLFGL.proto\"\x89\x01\n\x1aWindFieldDungeonSettleInfo\x12\x1b\n\x13Unk3100_ABGAMIOBKAB\x18\x0b \x03(\r\x12\x1b\n\x13Unk3100_MPGPNBOHCMC\x18\x07 \x03(\r\x12\x31\n\x13Unk3100_AOFJAJACNAJ\x18\x02 \x01(\x0e\x32\x14.Unk3100_HJALLGOLFGLb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WindFieldDungeonSettleInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINDFIELDDUNGEONSETTLEINFO._serialized_start=64
  _WINDFIELDDUNGEONSETTLEINFO._serialized_end=201
# @@protoc_insertion_point(module_scope)
