# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinterCampGetCanGiveFriendItemRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'WinterCampGetCanGiveFriendItemRsp.proto\x1a\x0fItemParam.proto\"S\n!WinterCampGetCanGiveFriendItemRsp\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x12\x1d\n\titem_list\x18\x0e \x03(\x0b\x32\n.ItemParamb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WinterCampGetCanGiveFriendItemRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINTERCAMPGETCANGIVEFRIENDITEMRSP._serialized_start=60
  _WINTERCAMPGETCANGIVEFRIENDITEMRSP._serialized_end=143
# @@protoc_insertion_point(module_scope)
