# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinterCampRecvItemData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2
import ProfilePicture_pb2 as ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cWinterCampRecvItemData.proto\x1a\x0fItemParam.proto\x1a\x14ProfilePicture.proto\"\x80\x01\n\x16WinterCampRecvItemData\x12\x10\n\x08nickname\x18\x08 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\r\x12(\n\x0fprofile_picture\x18\x01 \x01(\x0b\x32\x0f.ProfilePicture\x12\x1d\n\titem_list\x18\x03 \x03(\x0b\x32\n.ItemParamb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WinterCampRecvItemData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINTERCAMPRECVITEMDATA._serialized_start=72
  _WINTERCAMPRECVITEMDATA._serialized_end=200
# @@protoc_insertion_point(module_scope)
