# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinterCampAcceptItemResultInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WinterCampAcceptItemResultInfo.proto\x1a\x0fItemParam.proto\"\x7f\n\x1eWinterCampAcceptItemResultInfo\x12\'\n\x13Unk3300_ILELLFNPDFJ\x18\x0f \x03(\x0b\x32\n.ItemParam\x12\'\n\x13Unk3300_JHKOMCFHAOG\x18\r \x03(\x0b\x32\n.ItemParam\x12\x0b\n\x03uid\x18\t \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WinterCampAcceptItemResultInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINTERCAMPACCEPTITEMRESULTINFO._serialized_start=57
  _WINTERCAMPACCEPTITEMRESULTINFO._serialized_end=184
# @@protoc_insertion_point(module_scope)
