# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinterCampStageInfoChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WinterCampStageInfo_pb2 as WinterCampStageInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%WinterCampStageInfoChangeNotify.proto\x1a\x19WinterCampStageInfo.proto\"x\n\x1fWinterCampStageInfoChangeNotify\x12*\n\x0c\x65xplore_info\x18\x05 \x01(\x0b\x32\x14.WinterCampStageInfo\x12)\n\x0b\x62\x61ttle_info\x18\x0f \x01(\x0b\x32\x14.WinterCampStageInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WinterCampStageInfoChangeNotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINTERCAMPSTAGEINFOCHANGENOTIFY._serialized_start=68
  _WINTERCAMPSTAGEINFOCHANGENOTIFY._serialized_end=188
# @@protoc_insertion_point(module_scope)
