# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinterCampAcceptAllGiveItemRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WinterCampAcceptItemResultInfo_pb2 as WinterCampAcceptItemResultInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WinterCampAcceptAllGiveItemRsp.proto\x1a$WinterCampAcceptItemResultInfo.proto\"s\n\x1eWinterCampAcceptAllGiveItemRsp\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12@\n\x17\x61\x63\x63\x65pt_item_result_info\x18\x01 \x03(\x0b\x32\x1f.WinterCampAcceptItemResultInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WinterCampAcceptAllGiveItemRsp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINTERCAMPACCEPTALLGIVEITEMRSP._serialized_start=78
  _WINTERCAMPACCEPTALLGIVEITEMRSP._serialized_end=193
# @@protoc_insertion_point(module_scope)
